/**
 * Single source of truth for every page on freetoolarena.com.
 *
 * Flip `published: true` to take a page live. Everything else — routes,
 * sitemap.xml, internal links, category indexes — derives from this file.
 */

export const SITE_URL = "https://freetoolarena.com";
export const SITE_NAME = "Free Tool Arena";
export const SITE_TAGLINE = "Free tools + clear guides that solve real problems.";
/**
 * Contact email shown on /contact, /privacy, /terms. Before launch, point
 * this at a real monitored inbox (forwarder like ImprovMX works fine).
 * Can be overridden via NEXT_PUBLIC_CONTACT_EMAIL without a code change.
 */
export const SITE_EMAIL =
  process.env.NEXT_PUBLIC_CONTACT_EMAIL || "hello@freetoolarena.com";

export type Category =
  | "money"
  | "productivity"
  | "health"
  | "text"
  | "dev"
  | "units"
  | "random"
  | "coding"
  | "writing"
  | "career"
  | "home"
  | "social"
  | "converters";

export type PageType = "tool" | "article";

export interface Page {
  slug: string;
  type: PageType;
  title: string;       // <title> tag content (keyword-rich)
  h1: string;          // visible H1
  description: string; // meta description (140–160 chars)
  keyword: string;     // primary keyword
  category: Category;
  related: string[];   // slugs of related pages (tools or articles)
  published?: boolean;
}

export const CATEGORIES: Record<Category, { label: string; blurb: string }> = {
  money: { label: "Money & Finance", blurb: "Budget, loan, interest, and paycheck math — in seconds." },
  productivity: { label: "Productivity", blurb: "Timers, planners, and routines for focused work." },
  health: { label: "Health & Fitness", blurb: "Quick calculators and plain-English habit guides." },
  text: { label: "Text & Writing Utilities", blurb: "Count, format, clean, and convert text in a tab." },
  dev: { label: "Developer Utilities", blurb: "Formatters, generators, and regex tools for daily dev work." },
  units: { label: "Unit Converters", blurb: "Length, speed, temperature, and more — no ads, no math." },
  random: { label: "Random & Fun", blurb: "Coin flips, dice, and decision makers when you just need an answer." },
  coding: { label: "Coding & Tech", blurb: "Learn to code, ship your first project, land the dev job." },
  writing: { label: "Writing & Content", blurb: "Write better, start a blog, grow an audience online." },
  career: { label: "Career & Growth", blurb: "Interviews, résumés, promotions, and smart career moves." },
  home: { label: "Home & Life", blurb: "A calmer, cleaner, better-run home life — one habit at a time." },
  social: { label: "Relationships & Social", blurb: "Friendships, hard conversations, and social skills that travel." },
  converters: { label: "File & Format Converters", blurb: "PDFs, images, data formats — converted in your browser, offline-safe." },
};

export const PAGES: Page[] = [
  // -------------------- TOOLS: MONEY (10) --------------------
  { slug: "tip-calculator", type: "tool", category: "money",
    title: "Tip Calculator — Fast, Free, Split Bill Included",
    h1: "Tip Calculator",
    description: "Free tip calculator. Enter the bill, pick a tip percent, split between any number of people. Works on mobile, no ads, instant results.",
    keyword: "tip calculator",
    related: ["budget-calculator", "how-to-save-money-fast", "paycheck-calculator"],
    published: true },
  { slug: "loan-calculator", type: "tool", category: "money",
    title: "Loan Calculator — Monthly Payment & Total Interest",
    h1: "Loan Calculator",
    description: "Work out monthly payments and total interest on any loan. Enter amount, rate, and term — get a clear breakdown in seconds.",
    keyword: "loan calculator",
    related: ["mortgage-calculator", "debt-payoff-calculator", "how-to-pay-off-debt-fast"],
    published: true },
  { slug: "mortgage-calculator", type: "tool", category: "money",
    title: "Mortgage Calculator — Monthly Payment Estimator",
    h1: "Mortgage Calculator",
    description: "Estimate your monthly mortgage payment, total interest, and payoff schedule. Free, fast, and mobile-friendly.",
    keyword: "mortgage calculator",
    related: ["loan-calculator", "budget-calculator", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "compound-interest-calculator", type: "tool", category: "money",
    title: "Compound Interest Calculator — See Your Money Grow",
    h1: "Compound Interest Calculator",
    description: "See how much your money grows with compound interest. Add starting balance, monthly contributions, and watch the curve.",
    keyword: "compound interest calculator",
    related: ["savings-goal-calculator", "how-to-start-investing-with-100-dollars", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "savings-goal-calculator", type: "tool", category: "money",
    title: "Savings Goal Calculator — Reach Your Target on Time",
    h1: "Savings Goal Calculator",
    description: "Set a goal, a deadline, and see exactly how much to save each month. Plan a vacation, emergency fund, or down payment.",
    keyword: "savings goal calculator",
    related: ["compound-interest-calculator", "how-to-build-an-emergency-fund", "budget-calculator"],
    published: true },
  { slug: "budget-calculator", type: "tool", category: "money",
    title: "Monthly Budget Calculator — Free & Instant",
    h1: "Monthly Budget Calculator",
    description: "Enter your income and expenses, see what's left, and spot where you can cut. A simple monthly budget calculator that works.",
    keyword: "monthly budget calculator",
    related: ["tip-calculator", "how-to-make-a-monthly-budget", "how-to-save-money-fast"],
    published: true },
  { slug: "paycheck-calculator", type: "tool", category: "money",
    title: "Paycheck Calculator — Estimate Your Take-Home Pay",
    h1: "Paycheck Calculator",
    description: "Estimate your take-home pay after federal tax, state tax, and common deductions. Fast, free, updated for 2026.",
    keyword: "paycheck calculator",
    related: ["budget-calculator", "how-to-negotiate-salary", "how-to-save-on-taxes"],
    published: true },
  { slug: "roi-calculator", type: "tool", category: "money",
    title: "ROI Calculator — Return on Investment in Seconds",
    h1: "ROI Calculator",
    description: "Calculate return on investment (ROI) as a percentage or dollar amount. Enter cost, return, and time period — done.",
    keyword: "ROI calculator",
    related: ["compound-interest-calculator", "how-to-start-investing-with-100-dollars", "how-to-make-passive-income"],
    published: true },
  { slug: "currency-converter", type: "tool", category: "money",
    title: "Currency Converter — Live ECB Rates, Free",
    h1: "Currency Converter",
    description: "Convert between 15 major currencies using live mid-market rates from the European Central Bank. Manual override for custom rates.",
    keyword: "currency converter",
    related: ["unit-converter", "how-to-pack-for-travel", "budget-calculator"],
    published: true },
  { slug: "debt-payoff-calculator", type: "tool", category: "money",
    title: "Debt Payoff Calculator — Snowball or Avalanche",
    h1: "Debt Payoff Calculator",
    description: "See how fast you can clear debt with snowball or avalanche strategy. Enter balances, rates, and extra payment.",
    keyword: "debt payoff calculator",
    related: ["loan-calculator", "how-to-pay-off-debt-fast", "budget-calculator"],
    published: true },

  // -------------------- TOOLS: PRODUCTIVITY (9) --------------------
  { slug: "pomodoro-timer", type: "tool", category: "productivity",
    title: "Pomodoro Timer — Free Online 25/5 Focus Timer",
    h1: "Pomodoro Timer",
    description: "Free online pomodoro timer. 25 minutes of focus, 5-minute breaks, long break every 4 rounds. Customizable, works in any browser.",
    keyword: "pomodoro timer online",
    related: ["countdown-timer", "how-to-use-pomodoro-technique", "how-to-stay-productive-daily"],
    published: true },
  { slug: "countdown-timer", type: "tool", category: "productivity",
    title: "Online Countdown Timer — Free & Full-Screen",
    h1: "Countdown Timer",
    description: "Set a countdown timer for any duration, go full-screen, and hear a sound when it finishes. Free, no sign-up.",
    keyword: "countdown timer",
    related: ["pomodoro-timer", "how-to-use-pomodoro-technique", "how-to-focus-better"],
    published: true },
  { slug: "stopwatch", type: "tool", category: "productivity",
    title: "Online Stopwatch — Precise & Free",
    h1: "Online Stopwatch",
    description: "Free online stopwatch with lap times, millisecond precision, and a clean full-screen view. Works on any device.",
    keyword: "online stopwatch",
    related: ["countdown-timer", "pomodoro-timer", "how-to-plan-your-week"],
    published: true },
  { slug: "to-do-list", type: "tool", category: "productivity",
    title: "Online To-Do List — Free, No Sign-Up",
    h1: "Online To-Do List",
    description: "A simple, no-sign-up online to-do list. Add tasks, tick them off, reorder with a click. Saves in your browser.",
    keyword: "online to-do list",
    related: ["pomodoro-timer", "how-to-prioritize-tasks", "how-to-plan-your-week"],
    published: true },
  { slug: "habit-tracker", type: "tool", category: "productivity",
    title: "Habit Tracker — Free Online Daily Tracker",
    h1: "Habit Tracker",
    description: "Track daily habits for 30, 60, or 90 days. See your streak grow. Free, private, saves in your browser only.",
    keyword: "habit tracker online",
    related: ["to-do-list", "how-to-build-good-habits", "how-to-break-bad-habits"],
    published: true },
  { slug: "reading-time-estimator", type: "tool", category: "productivity",
    title: "Reading Time Estimator — Paste & Go",
    h1: "Reading Time Estimator",
    description: "Paste any text and get reading time in seconds. Based on average adult reading speed, adjustable for slow or fast readers.",
    keyword: "reading time estimator",
    related: ["word-counter", "how-to-read-more-books", "readability-score-checker"],
    published: true },
  { slug: "meeting-cost-calculator", type: "tool", category: "productivity",
    title: "Meeting Cost Calculator — What Is This Meeting Costing?",
    h1: "Meeting Cost Calculator",
    description: "Calculate the real cost of your meeting. Enter attendees, salaries, and duration — see the total burn in dollars.",
    keyword: "meeting cost calculator",
    related: ["paycheck-calculator", "how-to-give-a-great-presentation", "how-to-work-remotely"],
    published: true },
  { slug: "time-zone-converter", type: "tool", category: "productivity",
    title: "Time Zone Converter — Fast, Free, Accurate",
    h1: "Time Zone Converter",
    description: "Convert any time between any two time zones. Handles DST automatically. Great for scheduling across teams.",
    keyword: "time zone converter",
    related: ["public-holidays", "countdown-timer", "how-to-work-remotely"],
    published: true },
  { slug: "public-holidays", type: "tool", category: "productivity",
    title: "Public Holidays Lookup — Any Country, Any Year",
    h1: "Public Holidays Lookup",
    description: "See every public holiday for any country and year. Live data from Nager.Date — great for planning PTO, travel, or cross-border meetings.",
    keyword: "public holidays by country",
    related: ["time-zone-converter", "countdown-timer", "how-to-plan-your-week"],
    published: true },

  // -------------------- TOOLS: HEALTH (6) --------------------
  { slug: "bmi-calculator", type: "tool", category: "health",
    title: "BMI Calculator — Free & Metric/Imperial",
    h1: "BMI Calculator",
    description: "Calculate Body Mass Index in metric or imperial units. See your category and what it means, in plain English.",
    keyword: "BMI calculator",
    related: ["calorie-calculator", "water-intake-calculator", "how-to-sleep-better"],
    published: true },
  { slug: "calorie-calculator", type: "tool", category: "health",
    title: "Calorie Calculator — Daily Intake in Seconds",
    h1: "Calorie Calculator",
    description: "Estimate your daily calorie needs based on age, activity, and goals (lose, maintain, or gain). Free and private.",
    keyword: "calorie calculator",
    related: ["bmi-calculator", "water-intake-calculator", "how-to-meal-prep"],
    published: true },
  { slug: "water-intake-calculator", type: "tool", category: "health",
    title: "Water Intake Calculator — How Much Should You Drink?",
    h1: "Daily Water Intake Calculator",
    description: "Calculate how much water you should drink per day based on weight, activity, and climate. Liters and ounces.",
    keyword: "daily water intake calculator",
    related: ["calorie-calculator", "how-to-drink-more-water", "bmi-calculator"],
    published: true },
  { slug: "ideal-weight-calculator", type: "tool", category: "health",
    title: "Ideal Weight Calculator — Multiple Formulas",
    h1: "Ideal Weight Calculator",
    description: "See your ideal weight across several medical formulas (Devine, Robinson, Miller). Honest ranges, no fad claims.",
    keyword: "ideal weight calculator",
    related: ["bmi-calculator", "calorie-calculator", "beginner-workout-plan-at-home"],
    published: true },
  { slug: "running-pace-calculator", type: "tool", category: "health",
    title: "Running Pace Calculator — Pace, Time, Distance",
    h1: "Running Pace Calculator",
    description: "Calculate pace, finish time, or distance for any run. Supports km and miles. Perfect for 5K, 10K, half, and marathon training.",
    keyword: "running pace calculator",
    related: ["how-to-start-running", "calorie-calculator", "stopwatch"],
    published: true },
  { slug: "macro-calculator", type: "tool", category: "health",
    title: "Macro Calculator — Protein, Carbs, Fat per Day",
    h1: "Macro Calculator",
    description: "Get your daily protein, carb, and fat targets based on calories and goals. Free, no sign-up.",
    keyword: "macro calculator",
    related: ["calorie-calculator", "how-to-build-muscle-as-a-beginner", "how-to-eat-healthy-on-a-budget"],
    published: true },

  // -------------------- TOOLS: TEXT (8) --------------------
  { slug: "word-counter", type: "tool", category: "text",
    title: "Word Counter — Free Online Word & Character Count",
    h1: "Word Counter",
    description: "Free word counter. Paste text and see words, characters, sentences, and reading time instantly. Works offline after load.",
    keyword: "word counter",
    related: ["character-counter", "readability-score-checker", "how-to-learn-coding-fast"],
    published: true },
  { slug: "character-counter", type: "tool", category: "text",
    title: "Character Counter — With & Without Spaces",
    h1: "Character Counter",
    description: "Count characters with and without spaces. See limits for Twitter, SMS, meta descriptions, and more.",
    keyword: "character counter",
    related: ["word-counter", "json-formatter", "how-to-stay-productive-daily"],
    published: true },
  { slug: "case-converter", type: "tool", category: "text",
    title: "Case Converter — UPPER, lower, Title, camelCase",
    h1: "Case Converter",
    description: "Convert text to UPPERCASE, lowercase, Title Case, Sentence case, camelCase, snake_case, kebab-case. One click.",
    keyword: "case converter online",
    related: ["slug-generator", "character-counter", "word-counter"],
    published: true },
  { slug: "text-reverser", type: "tool", category: "text",
    title: "Text Reverser — Flip Words, Letters, Sentences",
    h1: "Text Reverser",
    description: "Reverse any text. Flip characters, reverse word order, or reverse sentence order. Free and instant.",
    keyword: "text reverser",
    related: ["case-converter", "word-counter", "random-name-generator"],
    published: true },
  { slug: "slug-generator", type: "tool", category: "text",
    title: "URL Slug Generator — SEO-Friendly Slugs Instantly",
    h1: "URL Slug Generator",
    description: "Turn any title into a clean, SEO-friendly URL slug. Lowercase, dashes, no special characters. Copy with one click.",
    keyword: "URL slug generator",
    related: ["case-converter", "seo-basics-for-beginners", "how-to-start-a-blog"],
    published: true },
  { slug: "lorem-ipsum-generator", type: "tool", category: "text",
    title: "Lorem Ipsum Generator — Paragraphs, Words, Sentences",
    h1: "Lorem Ipsum Generator",
    description: "Generate lorem ipsum placeholder text by paragraph, sentence, or word count. Classic or alternate variants.",
    keyword: "lorem ipsum generator",
    related: ["word-counter", "character-counter", "how-to-start-a-blog"],
    published: true },
  { slug: "readability-score-checker", type: "tool", category: "text",
    title: "Readability Score Checker — Flesch Reading Ease",
    h1: "Readability Score Checker",
    description: "Paste text to see Flesch Reading Ease, Flesch-Kincaid grade, and a plain-English recommendation. Free.",
    keyword: "readability score checker",
    related: ["word-counter", "how-to-write-better", "how-to-improve-grammar"],
    published: true },
  { slug: "typing-speed-test", type: "tool", category: "text",
    title: "Typing Speed Test — Free WPM Tester",
    h1: "Typing Speed Test",
    description: "Test your typing speed in words per minute (WPM) with accuracy scoring. 1, 3, or 5 minute tests. Free.",
    keyword: "typing speed test",
    related: ["word-counter", "stopwatch", "how-to-learn-coding-fast"],
    published: true },

  // -------------------- TOOLS: DEV (10) --------------------
  { slug: "json-formatter", type: "tool", category: "dev",
    title: "JSON Formatter — Validate, Format, Minify",
    h1: "JSON Formatter",
    description: "Paste JSON to format, validate, and minify. Clear error messages with line numbers. Free and runs in your browser.",
    keyword: "JSON formatter",
    related: ["json-to-csv", "base64-encoder-decoder", "how-to-learn-coding-fast"],
    published: true },
  { slug: "json-to-csv", type: "tool", category: "dev",
    title: "JSON to CSV Converter — Free & Fast",
    h1: "JSON to CSV Converter",
    description: "Convert JSON arrays to CSV instantly. Auto-detects headers, handles nested fields, exports to file.",
    keyword: "JSON to CSV converter",
    related: ["json-formatter", "url-encoder-decoder", "how-to-write-clean-code"],
    published: true },
  { slug: "base64-encoder-decoder", type: "tool", category: "dev",
    title: "Base64 Encoder / Decoder — Free Online",
    h1: "Base64 Encoder & Decoder",
    description: "Encode text to base64 or decode base64 back to text. UTF-8 safe. Runs entirely in your browser.",
    keyword: "base64 encoder decoder",
    related: ["url-encoder-decoder", "json-formatter", "password-generator"],
    published: true },
  { slug: "url-encoder-decoder", type: "tool", category: "dev",
    title: "URL Encoder / Decoder — Percent-Encoding Made Easy",
    h1: "URL Encoder & Decoder",
    description: "Encode URLs for safe use in links and query strings, or decode encoded URLs back to readable text.",
    keyword: "URL encoder decoder",
    related: ["base64-encoder-decoder", "slug-generator", "json-formatter"],
    published: true },
  { slug: "regex-tester", type: "tool", category: "dev",
    title: "Regex Tester — Test Regular Expressions Online",
    h1: "Regex Tester",
    description: "Test regular expressions against sample text with live match highlighting. Supports common flags and groups.",
    keyword: "regex tester online",
    related: ["json-formatter", "how-to-debug-code-effectively", "how-to-write-clean-code"],
    published: true },
  { slug: "uuid-generator", type: "tool", category: "dev",
    title: "UUID Generator — v4 (Random) & v1 (Timestamp)",
    h1: "UUID Generator",
    description: "Generate one or many UUIDs (v4 random or v1 timestamp). Copy single or bulk, free and runs locally.",
    keyword: "UUID generator",
    related: ["password-generator", "password-breach-checker", "how-to-learn-coding-fast"],
    published: true },
  { slug: "markdown-to-html", type: "tool", category: "dev",
    title: "Markdown to HTML Converter — Free Online",
    h1: "Markdown to HTML Converter",
    description: "Paste Markdown, get clean HTML. Supports tables, code blocks, and task lists. Runs in your browser.",
    keyword: "markdown to HTML converter",
    related: ["json-formatter", "how-to-start-a-blog", "how-to-write-clean-code"],
    published: true },
  { slug: "password-generator", type: "tool", category: "dev",
    title: "Password Generator — Strong, Random, Free",
    h1: "Password Generator",
    description: "Generate strong random passwords. Choose length, symbols, numbers, and avoid lookalikes. Runs locally.",
    keyword: "password generator",
    related: ["password-breach-checker", "uuid-generator", "how-to-learn-coding-fast"],
    published: true },
  { slug: "password-breach-checker", type: "tool", category: "dev",
    title: "Password Breach Checker — Is Yours Leaked? (HIBP)",
    h1: "Password Breach Checker",
    description: "Check if a password has appeared in a known data breach. Uses HaveIBeenPwned k-anonymity — your password never leaves the browser.",
    keyword: "password breach checker",
    related: ["password-generator", "ip-lookup", "uuid-generator"],
    published: true },
  { slug: "ip-lookup", type: "tool", category: "dev",
    title: "What Is My IP — Public IP + Location Lookup",
    h1: "What Is My IP",
    description: "See your public IP, approximate city, ISP, and time zone. Live, in your browser — we never see the request.",
    keyword: "what is my ip",
    related: ["password-breach-checker", "time-zone-converter", "public-holidays"],
    published: true },

  // -------------------- TOOLS: UNITS (5) --------------------
  { slug: "unit-converter", type: "tool", category: "units",
    title: "Unit Converter — Length, Weight, Volume & More",
    h1: "Unit Converter",
    description: "Free universal unit converter. Length, weight, volume, area, speed, energy, and more. All in one place.",
    keyword: "unit converter",
    related: ["temperature-converter", "age-calculator", "bmi-calculator"],
    published: true },
  { slug: "temperature-converter", type: "tool", category: "units",
    title: "Temperature Converter — Celsius, Fahrenheit, Kelvin",
    h1: "Temperature Converter",
    description: "Convert between Celsius, Fahrenheit, and Kelvin instantly. Live conversion as you type.",
    keyword: "temperature converter",
    related: ["unit-converter", "age-calculator", "bmi-calculator"],
    published: true },
  { slug: "length-converter", type: "tool", category: "units",
    title: "Length Converter — Meters, Feet, Miles, Inches",
    h1: "Length Converter",
    description: "Convert length units: meters, feet, inches, miles, kilometers, yards. Fast, free, and mobile-friendly.",
    keyword: "length converter",
    related: ["unit-converter", "speed-converter", "running-pace-calculator"],
    published: true },
  { slug: "speed-converter", type: "tool", category: "units",
    title: "Speed Converter — mph, km/h, m/s, knots",
    h1: "Speed Converter",
    description: "Convert between mph, km/h, m/s, knots, and feet per second. Live conversion, no ads.",
    keyword: "speed converter",
    related: ["unit-converter", "length-converter", "running-pace-calculator"],
    published: true },
  { slug: "age-calculator", type: "tool", category: "units",
    title: "Age Calculator — Years, Months, Days",
    h1: "Age Calculator",
    description: "Calculate exact age in years, months, and days from any birth date to any target date.",
    keyword: "age calculator",
    related: ["countdown-timer", "unit-converter", "temperature-converter"],
    published: true },

  // -------------------- TOOLS: RANDOM (5) --------------------
  { slug: "random-name-generator", type: "tool", category: "random",
    title: "Random Name Generator — Characters, Babies, Brands",
    h1: "Random Name Generator",
    description: "Generate random first and last names across styles: modern, classic, fantasy, brand-style. Free and fast.",
    keyword: "random name generator",
    related: ["random-number-generator", "uuid-generator", "decision-maker"],
    published: true },
  { slug: "random-number-generator", type: "tool", category: "random",
    title: "Random Number Generator — Any Range, Any Count",
    h1: "Random Number Generator",
    description: "Generate random numbers in any range, with or without duplicates. Great for draws, games, and testing.",
    keyword: "random number generator",
    related: ["dice-roller", "coin-flip", "uuid-generator"],
    published: true },
  { slug: "coin-flip", type: "tool", category: "random",
    title: "Online Coin Flip — Heads or Tails, Instant",
    h1: "Online Coin Flip",
    description: "Flip a virtual coin. Fair, fast, and animated. Flip one or many, with a running heads/tails tally.",
    keyword: "online coin flip",
    related: ["dice-roller", "age-calculator", "password-generator"],
    published: true },
  { slug: "dice-roller", type: "tool", category: "random",
    title: "Online Dice Roller — D6, D20, & Custom",
    h1: "Online Dice Roller",
    description: "Roll dice online. Supports D4, D6, D8, D10, D12, D20, and custom sides. Roll multiple dice at once.",
    keyword: "online dice roller",
    related: ["coin-flip", "age-calculator", "password-generator"],
    published: true },
  { slug: "decision-maker", type: "tool", category: "random",
    title: "Yes or No Decision Maker — Free Online",
    h1: "Yes or No Decision Maker",
    description: "Can't decide? Get a random yes or no, or pick from a custom list of options. Free and private.",
    keyword: "yes or no decision maker",
    related: ["coin-flip", "dice-roller", "random-name-generator"],
    published: true },

  // -------------------- ARTICLES: MONEY (20) --------------------
  { slug: "how-to-save-money-fast", type: "article", category: "money",
    title: "How to Save Money Fast — 15 Real Tactics That Work",
    h1: "How to Save Money Fast",
    description: "Save money fast with 15 tactics that actually work: automate savings, cut three categories, raise your income floor. No gimmicks.",
    keyword: "how to save money fast",
    related: ["budget-calculator", "tip-calculator", "how-to-build-an-emergency-fund", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "best-side-hustles-for-beginners", type: "article", category: "money",
    title: "Best Side Hustles for Beginners (2026)",
    h1: "The Best Side Hustles for Beginners",
    description: "Honest side hustle list for beginners: what pays now, what takes months, what's a scam. Time vs money ranked.",
    keyword: "best side hustles for beginners",
    related: ["how-to-start-a-business-with-no-money", "how-to-make-passive-income", "how-to-increase-your-income"],
    published: true },
  { slug: "how-to-start-investing-with-100-dollars", type: "article", category: "money",
    title: "How to Start Investing With $100 (Step-by-Step)",
    h1: "How to Start Investing With $100",
    description: "A beginner walkthrough: pick a broker, buy a low-cost index fund, automate. What to avoid. Real numbers.",
    keyword: "how to start investing with $100",
    related: ["compound-interest-calculator", "how-to-save-for-retirement", "how-to-pay-off-debt-fast"],
    published: true },
  { slug: "how-to-make-a-monthly-budget", type: "article", category: "money",
    title: "How to Make a Monthly Budget (That You'll Actually Use)",
    h1: "How to Make a Monthly Budget",
    description: "Build a monthly budget in 20 minutes. The 50/30/20 rule, zero-based, and how to pick what fits your life.",
    keyword: "how to make a monthly budget",
    related: ["budget-calculator", "how-to-save-money-fast", "how-to-focus-better"],
    published: true },
  { slug: "how-to-pay-off-debt-fast", type: "article", category: "money",
    title: "How to Pay Off Debt Fast — Snowball vs Avalanche",
    h1: "How to Pay Off Debt Fast",
    description: "Compare snowball and avalanche methods with real math. Which wins in dollars, which wins in momentum.",
    keyword: "how to pay off debt fast",
    related: ["budget-calculator", "how-to-track-expenses", "how-to-save-money-fast"],
    published: true },
  { slug: "how-to-build-credit", type: "article", category: "money",
    title: "How to Build Credit From Zero (Beginner's Guide)",
    h1: "How to Build Credit From Zero",
    description: "Build a credit score from 0 to 700+ with simple moves: secured card, on-time payments, and what to avoid.",
    keyword: "how to build credit",
    related: ["how-to-pay-off-debt-fast", "how-to-make-a-monthly-budget", "debt-payoff-calculator"],
    published: true },
  { slug: "how-to-make-passive-income", type: "article", category: "money",
    title: "How to Make Passive Income — Real Streams in 2026",
    h1: "How to Make Passive Income",
    description: "Passive income without the hype. Honest breakdown of seven streams: setup cost, effort, realistic return.",
    keyword: "how to make passive income",
    related: ["best-side-hustles-for-beginners", "how-to-start-investing-with-100-dollars", "roi-calculator"],
    published: true },
  { slug: "how-to-save-for-retirement", type: "article", category: "money",
    title: "How to Save for Retirement (Start at Any Age)",
    h1: "How to Save for Retirement",
    description: "A plain-English retirement plan: how much to save, which accounts, how age changes the math. No jargon.",
    keyword: "how to save for retirement",
    related: ["budget-calculator", "how-to-build-an-emergency-fund", "how-to-save-money-fast"],
    published: true },
  { slug: "how-to-save-for-a-house", type: "article", category: "money",
    title: "How to Save for a House — Down Payment Plan",
    h1: "How to Save for a House",
    description: "Build a realistic down-payment plan. How much you need, where to park it, and timelines by city.",
    keyword: "how to save for a house",
    related: ["mortgage-calculator", "savings-goal-calculator", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "how-to-negotiate-salary", type: "article", category: "money",
    title: "How to Negotiate Salary — Scripts That Actually Work",
    h1: "How to Negotiate Salary",
    description: "Negotiate salary with confidence: prep, anchor, respond, counter. Real scripts for email and calls.",
    keyword: "how to negotiate salary",
    related: ["how-to-ace-a-job-interview", "how-to-write-a-resume", "budget-calculator"],
    published: true },
  { slug: "how-to-start-a-business-with-no-money", type: "article", category: "money",
    title: "How to Start a Business With No Money",
    h1: "How to Start a Business With No Money",
    description: "Bootstrap a business from $0: ideas that need only time, validating cheaply, and the first 10 customers.",
    keyword: "how to start a business with no money",
    related: ["best-side-hustles-for-beginners", "how-to-make-passive-income", "how-to-increase-your-income"],
    published: true },
  { slug: "how-to-save-on-groceries", type: "article", category: "money",
    title: "How to Save on Groceries — 12 Habits That Stick",
    h1: "How to Save on Groceries",
    description: "Cut your grocery bill 20-30% with habits, not coupons. Meal planning, store choice, and the 3-item rule.",
    keyword: "how to save on groceries",
    related: ["how-to-meal-prep", "budget-calculator", "how-to-track-expenses"],
    published: true },
  { slug: "how-to-live-below-your-means", type: "article", category: "money",
    title: "How to Live Below Your Means (Without Feeling Deprived)",
    h1: "How to Live Below Your Means",
    description: "Spend less than you earn, enjoy it, and build wealth. Practical mindset + mechanics that last.",
    keyword: "how to live below your means",
    related: ["how-to-make-a-monthly-budget", "how-to-avoid-lifestyle-creep", "how-to-save-money-fast"],
    published: true },
  { slug: "how-to-avoid-lifestyle-creep", type: "article", category: "money",
    title: "How to Avoid Lifestyle Creep After a Raise",
    h1: "How to Avoid Lifestyle Creep",
    description: "Got a raise? Don't spend it. How to lock in savings automatically and keep your life the same.",
    keyword: "how to avoid lifestyle creep",
    related: ["how-to-live-below-your-means", "how-to-make-a-monthly-budget", "how-to-save-for-retirement"],
    published: true },
  { slug: "how-to-track-expenses", type: "article", category: "money",
    title: "How to Track Expenses — Simple Systems That Work",
    h1: "How to Track Expenses",
    description: "Three systems to track expenses: paper, spreadsheet, or app. Pick one, use it for a month, decide.",
    keyword: "how to track expenses",
    related: ["budget-calculator", "how-to-make-a-monthly-budget", "how-to-save-money-fast"],
    published: true },
  { slug: "best-apps-to-save-money", type: "article", category: "money",
    title: "Best Apps to Save Money in 2026",
    h1: "The Best Apps to Save Money",
    description: "Honest reviews of the best money-saving apps. Which are worth it, which are ads, which to skip.",
    keyword: "best apps to save money",
    related: ["how-to-save-money-fast", "how-to-track-expenses", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "how-to-teach-kids-about-money", type: "article", category: "money",
    title: "How to Teach Kids About Money (By Age)",
    h1: "How to Teach Kids About Money",
    description: "Age-by-age guide to teaching kids money: ages 4-7, 8-12, and teens. Simple lessons that actually stick.",
    keyword: "how to teach kids about money",
    related: ["how-to-make-a-monthly-budget", "how-to-build-credit", "how-to-save-money-fast"],
    published: true },
  { slug: "how-to-build-an-emergency-fund", type: "article", category: "money",
    title: "How to Build an Emergency Fund (From Zero)",
    h1: "How to Build an Emergency Fund",
    description: "How much you really need, where to keep it, and how to get there in 6 months even on a tight budget.",
    keyword: "how to build an emergency fund",
    related: ["budget-calculator", "how-to-save-money-fast", "how-to-make-a-monthly-budget"],
    published: true },
  { slug: "how-to-increase-your-income", type: "article", category: "money",
    title: "How to Increase Your Income — 7 Proven Paths",
    h1: "How to Increase Your Income",
    description: "Raise income without burning out: raise, promotion, side hustle, freelance, switch jobs. Ranked by speed.",
    keyword: "how to increase your income",
    related: ["how-to-negotiate-salary", "best-side-hustles-for-beginners", "how-to-switch-careers"],
    published: true },
  { slug: "how-to-save-on-taxes", type: "article", category: "money",
    title: "How to Save on Taxes — Legal Moves Anyone Can Use",
    h1: "How to Save on Taxes",
    description: "Legit tax-saving moves: retirement contributions, HSA, deductions, credits. What most people miss.",
    keyword: "how to save on taxes",
    related: ["paycheck-calculator", "how-to-save-for-retirement", "how-to-make-a-monthly-budget"],
    published: true },

  // -------------------- ARTICLES: PRODUCTIVITY (15) --------------------
  { slug: "how-to-stay-productive-daily", type: "article", category: "productivity",
    title: "How to Stay Productive Daily — 9 Habits That Last",
    h1: "How to Stay Productive Daily",
    description: "Stay productive without hustle culture. Nine daily habits that keep output high and burnout away.",
    keyword: "how to stay productive daily",
    related: ["pomodoro-timer", "how-to-focus-better", "morning-routine-for-success", "how-to-stop-procrastinating"],
    published: true },
  { slug: "morning-routine-for-success", type: "article", category: "productivity",
    title: "Morning Routine for Success — What Actually Works",
    h1: "Morning Routine for Success",
    description: "Build a morning routine that sets up your day. Science-backed steps, realistic time blocks, no 4 a.m. talk.",
    keyword: "morning routine for success",
    related: ["how-to-wake-up-early", "how-to-stay-productive-daily", "how-to-focus-better"],
    published: true },
  { slug: "how-to-focus-better", type: "article", category: "productivity",
    title: "How to Focus Better — Deep Work in a Distracted World",
    h1: "How to Focus Better",
    description: "Focus for 90 minutes at a time with three mechanics: environment, rhythm, and the one-tab rule.",
    keyword: "how to focus better",
    related: ["pomodoro-timer", "how-to-stay-productive-daily", "how-to-learn-coding-fast"],
    published: true },
  { slug: "how-to-stop-procrastinating", type: "article", category: "productivity",
    title: "How to Stop Procrastinating — The 2-Minute Rule & More",
    h1: "How to Stop Procrastinating",
    description: "Stop procrastinating with tactics that beat willpower: 2-minute rule, task framing, and environment design.",
    keyword: "how to stop procrastinating",
    related: ["pomodoro-timer", "how-to-focus-better", "how-to-use-pomodoro-technique"],
    published: true },
  { slug: "time-management-tips-for-students", type: "article", category: "productivity",
    title: "Time Management Tips for Students — Study Smarter",
    h1: "Time Management Tips for Students",
    description: "Manage your time as a student: time-block classes + study, use the pomodoro technique, protect sleep.",
    keyword: "time management tips for students",
    related: ["pomodoro-timer", "how-to-plan-your-week", "how-to-take-better-notes"],
    published: true },
  { slug: "how-to-wake-up-early", type: "article", category: "productivity",
    title: "How to Wake Up Early (and Actually Enjoy It)",
    h1: "How to Wake Up Early",
    description: "Wake up early without hating life. Shift your bedtime in 15-minute steps, fix your first 10 minutes.",
    keyword: "how to wake up early",
    related: ["how-to-sleep-better", "how-to-build-good-habits", "countdown-timer"],
    published: true },
  { slug: "how-to-build-good-habits", type: "article", category: "productivity",
    title: "How to Build Good Habits (That Stick)",
    h1: "How to Build Good Habits",
    description: "Build habits that last: habit stacking, tiny actions, and the environment trick almost no one uses.",
    keyword: "how to build good habits",
    related: ["pomodoro-timer", "how-to-stop-procrastinating", "how-to-focus-better"],
    published: true },
  { slug: "how-to-break-bad-habits", type: "article", category: "productivity",
    title: "How to Break Bad Habits — Without Willpower",
    h1: "How to Break Bad Habits",
    description: "Break a bad habit by changing the cue, not the behavior. A simple framework with examples.",
    keyword: "how to break bad habits",
    related: ["how-to-build-good-habits", "how-to-reduce-stress", "how-to-stay-motivated"],
    published: true },
  { slug: "how-to-plan-your-week", type: "article", category: "productivity",
    title: "How to Plan Your Week — A 20-Minute System",
    h1: "How to Plan Your Week",
    description: "Plan your week in 20 minutes: review, pick the three that matter, time-block, protect energy peaks.",
    keyword: "how to plan your week",
    related: ["pomodoro-timer", "how-to-stay-productive-daily", "deep-work-strategies"],
    published: true },
  { slug: "how-to-work-from-home-productively", type: "article", category: "productivity",
    title: "How to Work From Home Productively",
    h1: "How to Work From Home Productively",
    description: "Work from home without burning out: dedicated space, hard edges on start/stop, and meeting hygiene.",
    keyword: "how to work from home productively",
    related: ["how-to-stay-productive-daily", "how-to-set-up-a-home-office", "how-to-work-remotely"],
    published: true },
  { slug: "deep-work-strategies", type: "article", category: "productivity",
    title: "Deep Work Strategies That Actually Scale",
    h1: "Deep Work Strategies",
    description: "Deep work, distilled: rhythmic vs monastic, how to schedule it, how to protect it, how to recover.",
    keyword: "deep work strategies",
    related: ["how-to-focus-better", "pomodoro-timer", "how-to-stop-procrastinating"],
    published: true },
  { slug: "how-to-use-pomodoro-technique", type: "article", category: "productivity",
    title: "How to Use the Pomodoro Technique — A Full Guide",
    h1: "How to Use the Pomodoro Technique",
    description: "The complete pomodoro guide: the rules, the common mistakes, and variations that work for coding or writing.",
    keyword: "how to use the pomodoro technique",
    related: ["pomodoro-timer", "countdown-timer", "how-to-focus-better", "how-to-stop-procrastinating"],
    published: true },
  { slug: "how-to-prioritize-tasks", type: "article", category: "productivity",
    title: "How to Prioritize Tasks — Eisenhower, MITs & More",
    h1: "How to Prioritize Tasks",
    description: "Three prioritization frameworks that actually get used: Eisenhower, MITs, and the 1-3-5 rule.",
    keyword: "how to prioritize tasks",
    related: ["to-do-list", "how-to-plan-your-week", "how-to-stay-productive-daily"],
    published: true },
  { slug: "how-to-beat-burnout", type: "article", category: "productivity",
    title: "How to Beat Burnout — Recover and Rebuild",
    h1: "How to Beat Burnout",
    description: "Burnout isn't laziness. A staged recovery plan: rest, reassess workload, rebuild boundaries.",
    keyword: "how to beat burnout",
    related: ["how-to-reduce-stress", "how-to-sleep-better", "how-to-stay-motivated"],
    published: true },
  { slug: "how-to-stay-motivated", type: "article", category: "productivity",
    title: "How to Stay Motivated — When the Spark Is Gone",
    h1: "How to Stay Motivated",
    description: "Motivation is unreliable. Systems that keep you moving when you don't feel like it — and why they work.",
    keyword: "how to stay motivated",
    related: ["how-to-build-good-habits", "how-to-stop-procrastinating", "how-to-beat-burnout"],
    published: true },

  // -------------------- ARTICLES: CODING (15) --------------------
  { slug: "how-to-learn-coding-fast", type: "article", category: "coding",
    title: "How to Learn Coding Fast — A 90-Day Plan",
    h1: "How to Learn Coding Fast",
    description: "Learn coding in 90 days with a realistic plan: one language, small projects, and the daily habit that makes it stick.",
    keyword: "how to learn coding fast",
    related: ["json-formatter", "best-programming-languages-to-learn", "how-to-build-a-developer-portfolio", "how-to-learn-python-in-30-days"],
    published: true },
  { slug: "best-programming-languages-to-learn", type: "article", category: "coding",
    title: "Best Programming Languages to Learn in 2026",
    h1: "Best Programming Languages to Learn",
    description: "The best languages to learn in 2026, ranked by job market, learning curve, and what you want to build.",
    keyword: "best programming languages to learn",
    related: ["how-to-learn-coding-fast", "how-to-learn-python-in-30-days", "how-to-get-your-first-developer-job"],
    published: true },
  { slug: "how-to-get-your-first-developer-job", type: "article", category: "coding",
    title: "How to Get Your First Developer Job",
    h1: "How to Get Your First Developer Job",
    description: "From zero to hired: what to build, how to apply, what recruiters actually want to see from juniors.",
    keyword: "how to get your first developer job",
    related: ["how-to-build-a-developer-portfolio", "how-to-prepare-for-coding-interviews", "how-to-ace-a-job-interview"],
    published: true },
  { slug: "how-to-build-a-developer-portfolio", type: "article", category: "coding",
    title: "How to Build a Developer Portfolio That Gets Interviews",
    h1: "How to Build a Developer Portfolio",
    description: "What makes a dev portfolio land interviews: the right 3 projects, a clean README, and a live demo.",
    keyword: "how to build a developer portfolio",
    related: ["how-to-get-your-first-developer-job", "how-to-learn-coding-fast", "how-to-contribute-to-open-source"],
    published: true },
  { slug: "how-to-write-clean-code", type: "article", category: "coding",
    title: "How to Write Clean Code — 12 Habits That Matter",
    h1: "How to Write Clean Code",
    description: "Clean code isn't style — it's empathy for the next reader. Twelve habits that make codebases better.",
    keyword: "how to write clean code",
    related: ["git-commands-every-developer-should-know", "how-to-prepare-for-coding-interviews", "how-to-learn-coding-fast"],
    published: true },
  { slug: "git-commands-every-developer-should-know", type: "article", category: "coding",
    title: "Git Commands Every Developer Should Know",
    h1: "Git Commands Every Developer Should Know",
    description: "The 20 git commands you'll use every day, with real examples and when to reach for each.",
    keyword: "git commands every developer should know",
    related: ["how-to-write-clean-code", "how-to-prepare-for-coding-interviews", "password-generator"],
    published: true },
  { slug: "how-to-prepare-for-coding-interviews", type: "article", category: "coding",
    title: "How to Prepare for Coding Interviews",
    h1: "How to Prepare for Coding Interviews",
    description: "A realistic prep plan: DS&A, systems, behavioral. How long it takes, what to skip.",
    keyword: "how to prepare for coding interviews",
    related: ["how-to-ace-a-job-interview", "how-to-learn-coding-fast", "countdown-timer"],
    published: true },
  { slug: "vscode-tips-and-tricks", type: "article", category: "coding",
    title: "VS Code Tips and Tricks — Level Up in an Hour",
    h1: "VS Code Tips and Tricks",
    description: "Keyboard shortcuts, multi-cursor, settings sync, and the extensions that actually earn their keep.",
    keyword: "VS Code tips and tricks",
    related: ["how-to-write-clean-code", "git-commands-every-developer-should-know", "how-to-debug-code-effectively"],
    published: true },
  { slug: "how-to-debug-code-effectively", type: "article", category: "coding",
    title: "How to Debug Code Effectively",
    h1: "How to Debug Code Effectively",
    description: "Debug faster by forming a hypothesis first, binary-searching the problem, and using the debugger properly.",
    keyword: "how to debug code effectively",
    related: ["how-to-write-clean-code", "regex-tester", "vscode-tips-and-tricks"],
    published: true },
  { slug: "how-to-contribute-to-open-source", type: "article", category: "coding",
    title: "How to Contribute to Open Source — A First-PR Guide",
    h1: "How to Contribute to Open Source",
    description: "Land your first open source PR: find a good-first-issue, read the contrib guide, keep the diff small.",
    keyword: "how to contribute to open source",
    related: ["git-commands-every-developer-should-know", "how-to-build-a-developer-portfolio", "how-to-learn-coding-fast"],
    published: true },
  { slug: "frontend-vs-backend-development", type: "article", category: "coding",
    title: "Frontend vs Backend Development — Which to Pick",
    h1: "Frontend vs Backend Development",
    description: "What each side actually does day to day, who tends to enjoy which, and why full-stack is usually the answer.",
    keyword: "frontend vs backend development",
    related: ["how-to-become-a-full-stack-developer", "best-programming-languages-to-learn", "how-to-learn-coding-fast"],
    published: true },
  { slug: "how-to-become-a-full-stack-developer", type: "article", category: "coding",
    title: "How to Become a Full Stack Developer",
    h1: "How to Become a Full Stack Developer",
    description: "A roadmap from zero to full-stack: HTML/CSS/JS, one frontend framework, one backend, one database.",
    keyword: "how to become a full stack developer",
    related: ["frontend-vs-backend-development", "how-to-learn-coding-fast", "how-to-build-a-developer-portfolio"],
    published: true },
  { slug: "rest-vs-graphql", type: "article", category: "coding",
    title: "REST vs GraphQL — When to Use Each",
    h1: "REST vs GraphQL",
    description: "REST and GraphQL compared honestly: developer experience, performance, tooling, and real-world fit.",
    keyword: "REST vs GraphQL",
    related: ["what-is-an-api", "how-to-become-a-full-stack-developer", "how-to-write-clean-code"],
    published: true },
  { slug: "what-is-an-api", type: "article", category: "coding",
    title: "What Is an API? A Plain-English Explainer",
    h1: "What Is an API?",
    description: "APIs explained without jargon: what they do, how they work, and why they're the glue of modern software.",
    keyword: "what is an API",
    related: ["rest-vs-graphql", "how-to-learn-coding-fast", "json-formatter"],
    published: true },
  { slug: "how-to-learn-python-in-30-days", type: "article", category: "coding",
    title: "How to Learn Python in 30 Days — Week by Week",
    h1: "How to Learn Python in 30 Days",
    description: "A 30-day Python plan: syntax, data structures, a real project. Daily time commitment: 1 hour.",
    keyword: "how to learn Python in 30 days",
    related: ["how-to-learn-coding-fast", "best-programming-languages-to-learn", "how-to-build-a-developer-portfolio"],
    published: true },

  // -------------------- ARTICLES: HEALTH (15) --------------------
  { slug: "how-to-sleep-better", type: "article", category: "health",
    title: "How to Sleep Better — 10 Habits Backed by Science",
    h1: "How to Sleep Better",
    description: "Sleep better tonight: ten habits that move the needle on sleep quality, without melatonin marketing.",
    keyword: "how to sleep better",
    related: ["how-to-reduce-stress", "how-to-wake-up-early", "countdown-timer"],
    published: true },
  { slug: "how-to-drink-more-water", type: "article", category: "health",
    title: "How to Drink More Water — 7 Habits That Stick",
    h1: "How to Drink More Water",
    description: "Drink more water without thinking about it: habit stacks, bottle tricks, and signals to watch for.",
    keyword: "how to drink more water",
    related: ["water-intake-calculator", "how-to-build-good-habits", "how-to-sleep-better"],
    published: true },
  { slug: "beginner-workout-plan-at-home", type: "article", category: "health",
    title: "Beginner Workout Plan at Home — 4 Weeks, No Gear",
    h1: "Beginner Workout Plan at Home",
    description: "A 4-week home workout for complete beginners. Bodyweight only, 20-30 minutes, three days a week.",
    keyword: "beginner workout plan at home",
    related: ["bmi-calculator", "how-to-start-running", "calorie-calculator"],
    published: true },
  { slug: "how-to-start-running", type: "article", category: "health",
    title: "How to Start Running — Couch to First 5K",
    h1: "How to Start Running",
    description: "Start running without hating it. A walk-run plan to your first 5K in 8 weeks, plus injury avoidance.",
    keyword: "how to start running",
    related: ["stopwatch", "beginner-workout-plan-at-home", "how-to-sleep-better"],
    published: true },
  { slug: "how-to-lose-belly-fat", type: "article", category: "health",
    title: "How to Lose Belly Fat — The Honest Version",
    h1: "How to Lose Belly Fat",
    description: "You can't spot-reduce. What actually works: calorie deficit, strength, sleep, stress. Honest and boring.",
    keyword: "how to lose belly fat",
    related: ["calorie-calculator", "beginner-workout-plan-at-home", "intermittent-fasting-for-beginners"],
    published: true },
  { slug: "intermittent-fasting-for-beginners", type: "article", category: "health",
    title: "Intermittent Fasting for Beginners",
    h1: "Intermittent Fasting for Beginners",
    description: "IF explained simply: 16:8, what to eat, common mistakes, and who should skip it. No hype.",
    keyword: "intermittent fasting for beginners",
    related: ["how-to-lose-belly-fat", "macro-calculator", "how-to-eat-healthy-on-a-budget"],
    published: true },
  { slug: "how-to-eat-healthy-on-a-budget", type: "article", category: "health",
    title: "How to Eat Healthy on a Budget",
    h1: "How to Eat Healthy on a Budget",
    description: "Eat well for less: the 10-item grocery staple list, batch cooking, and when frozen beats fresh.",
    keyword: "how to eat healthy on a budget",
    related: ["how-to-meal-prep", "how-to-save-on-groceries", "calorie-calculator"],
    published: true },
  { slug: "how-to-reduce-stress", type: "article", category: "health",
    title: "How to Reduce Stress — Daily Habits That Work",
    h1: "How to Reduce Stress",
    description: "Reduce stress with simple daily habits: breathwork, sleep, movement, and the 'worry window' trick.",
    keyword: "how to reduce stress",
    related: ["how-to-sleep-better", "pomodoro-timer", "how-to-build-good-habits"],
    published: true },
  { slug: "mindfulness-for-beginners", type: "article", category: "health",
    title: "Mindfulness for Beginners — A 10-Minute Start",
    h1: "Mindfulness for Beginners",
    description: "A realistic 10-minute intro to mindfulness. What it is, what it isn't, and a daily micro-practice.",
    keyword: "mindfulness for beginners",
    related: ["how-to-meditate-daily", "how-to-reduce-stress", "how-to-improve-mental-health"],
    published: true },
  { slug: "how-to-meditate-daily", type: "article", category: "health",
    title: "How to Meditate Daily (Even if You've Failed Before)",
    h1: "How to Meditate Daily",
    description: "Build a daily meditation habit: 3 minutes, same time, same trigger. No app required.",
    keyword: "how to meditate daily",
    related: ["mindfulness-for-beginners", "how-to-build-good-habits", "how-to-reduce-stress"],
    published: true },
  { slug: "how-to-build-muscle-as-a-beginner", type: "article", category: "health",
    title: "How to Build Muscle as a Beginner",
    h1: "How to Build Muscle as a Beginner",
    description: "Beginner muscle-building: progressive overload, sleep, protein. What matters in year one.",
    keyword: "how to build muscle as a beginner",
    related: ["macro-calculator", "beginner-workout-plan-at-home", "calorie-calculator"],
    published: true },
  { slug: "how-to-stretch-properly", type: "article", category: "health",
    title: "How to Stretch Properly — Dynamic vs Static",
    h1: "How to Stretch Properly",
    description: "Stretch without wasting time or risking injury: when to do dynamic, when static, and what to skip.",
    keyword: "how to stretch properly",
    related: ["how-to-start-running", "how-to-fix-posture", "beginner-workout-plan-at-home"],
    published: true },
  { slug: "how-to-fix-posture", type: "article", category: "health",
    title: "How to Fix Posture — Simple Daily Drills",
    h1: "How to Fix Posture",
    description: "Fix your posture with 5-minute daily drills. What to strengthen, what to stretch, what to stop doing.",
    keyword: "how to fix posture",
    related: ["how-to-stretch-properly", "how-to-set-up-a-home-office", "beginner-workout-plan-at-home"],
    published: true },
  { slug: "how-to-boost-energy-naturally", type: "article", category: "health",
    title: "How to Boost Energy Naturally — Without Caffeine",
    h1: "How to Boost Energy Naturally",
    description: "Sustainable energy without more coffee: light, movement, meal timing, and hydration.",
    keyword: "how to boost energy naturally",
    related: ["how-to-drink-more-water", "how-to-sleep-better", "how-to-reduce-stress"],
    published: true },
  { slug: "how-to-improve-mental-health", type: "article", category: "health",
    title: "How to Improve Mental Health — Small Daily Moves",
    h1: "How to Improve Mental Health",
    description: "Small, repeatable moves that build mental health over months: sleep, connection, movement, and help.",
    keyword: "how to improve mental health",
    related: ["how-to-reduce-stress", "mindfulness-for-beginners", "how-to-set-boundaries"],
    published: true },

  // -------------------- ARTICLES: WRITING (10) --------------------
  { slug: "how-to-write-better", type: "article", category: "writing",
    title: "How to Write Better — 10 Rules That Travel",
    h1: "How to Write Better",
    description: "Ten writing rules that work in essays, blog posts, and email. Cut words, pick nouns, kill throat-clearing.",
    keyword: "how to write better",
    related: ["word-counter", "character-counter", "how-to-start-a-blog"],
    published: true },
  { slug: "how-to-start-a-blog", type: "article", category: "writing",
    title: "How to Start a Blog — Step-by-Step for 2026",
    h1: "How to Start a Blog",
    description: "Start a blog in a weekend: platform, domain, first post, and a sane posting cadence you can hold.",
    keyword: "how to start a blog",
    related: ["seo-basics-for-beginners", "how-to-write-better", "slug-generator"],
    published: true },
  { slug: "how-to-grow-on-twitter", type: "article", category: "writing",
    title: "How to Grow on Twitter — From Zero to 10K",
    h1: "How to Grow on Twitter",
    description: "Grow a Twitter/X following with consistency, niche focus, and reply-first engagement. No buying followers.",
    keyword: "how to grow on Twitter",
    related: ["how-to-start-a-blog", "how-to-grow-on-youtube", "how-to-write-better"],
    published: true },
  { slug: "how-to-grow-on-youtube", type: "article", category: "writing",
    title: "How to Grow on YouTube — Beginner's Blueprint",
    h1: "How to Grow on YouTube",
    description: "The beginner YouTube blueprint: niche, title + thumbnail, first 10 videos, and the hook rule.",
    keyword: "how to grow on YouTube",
    related: ["how-to-grow-on-twitter", "how-to-start-a-blog", "seo-basics-for-beginners"],
    published: true },
  { slug: "seo-basics-for-beginners", type: "article", category: "writing",
    title: "SEO Basics for Beginners — A Zero-to-Rank Guide",
    h1: "SEO Basics for Beginners",
    description: "SEO from zero: keywords, on-page, links, and what matters vs what's noise. With a real workflow.",
    keyword: "SEO basics for beginners",
    related: ["slug-generator", "how-to-start-a-blog", "how-to-write-better"],
    published: true },
  { slug: "how-to-write-a-cover-letter", type: "article", category: "writing",
    title: "How to Write a Cover Letter That Gets Read",
    h1: "How to Write a Cover Letter",
    description: "Cover letters that actually get read: lead with the win, tie to the role, keep it one page.",
    keyword: "how to write a cover letter",
    related: ["how-to-write-a-resume", "how-to-ace-a-job-interview", "how-to-write-better"],
    published: true },
  { slug: "how-to-write-a-resume", type: "article", category: "writing",
    title: "How to Write a Resume (That Beats the ATS)",
    h1: "How to Write a Resume",
    description: "A resume the ATS reads and humans love: format, bullets that show impact, and what to cut.",
    keyword: "how to write a resume",
    related: ["how-to-ace-a-job-interview", "how-to-negotiate-salary", "character-counter"],
    published: true },
  { slug: "how-to-improve-grammar", type: "article", category: "writing",
    title: "How to Improve Grammar — Fast, Without a Textbook",
    h1: "How to Improve Grammar",
    description: "Improve grammar without a textbook: read aloud, learn your top 3 mistakes, and use a short checklist.",
    keyword: "how to improve grammar",
    related: ["how-to-write-better", "readability-score-checker", "word-counter"],
    published: true },
  { slug: "how-to-read-more-books", type: "article", category: "writing",
    title: "How to Read More Books — A Realistic System",
    h1: "How to Read More Books",
    description: "Read 30+ books a year without forcing it: 20-minute windows, book-abandon permission, and a simple list.",
    keyword: "how to read more books",
    related: ["reading-time-estimator", "how-to-take-better-notes", "how-to-build-good-habits"],
    published: true },
  { slug: "how-to-take-better-notes", type: "article", category: "writing",
    title: "How to Take Better Notes — Zettelkasten to Cornell",
    h1: "How to Take Better Notes",
    description: "Compare note-taking systems: Cornell, Zettelkasten, PARA. Which is worth it, which is overkill.",
    keyword: "how to take better notes",
    related: ["how-to-read-more-books", "how-to-write-better", "time-management-tips-for-students"],
    published: true },

  // -------------------- ARTICLES: CAREER (10) --------------------
  { slug: "how-to-network-effectively", type: "article", category: "career",
    title: "How to Network Effectively — For People Who Hate It",
    h1: "How to Network Effectively",
    description: "Network without cringe: give before you ask, keep a simple CRM, and how to follow up.",
    keyword: "how to network effectively",
    related: ["how-to-write-a-resume", "how-to-ace-a-job-interview", "how-to-write-a-cover-letter"],
    published: true },
  { slug: "how-to-ace-a-job-interview", type: "article", category: "career",
    title: "How to Ace a Job Interview — STAR Method & More",
    h1: "How to Ace a Job Interview",
    description: "Ace your interview: STAR answers, the right questions to ask, and the 5-minute pre-interview ritual.",
    keyword: "how to ace a job interview",
    related: ["how-to-prepare-for-coding-interviews", "how-to-write-a-resume", "how-to-negotiate-salary"],
    published: true },
  { slug: "how-to-quit-your-job-professionally", type: "article", category: "career",
    title: "How to Quit Your Job Professionally",
    h1: "How to Quit Your Job Professionally",
    description: "Quit the right way: two-week notice, a clean handoff, and a resignation letter template.",
    keyword: "how to quit your job professionally",
    related: ["how-to-switch-careers", "how-to-write-professional-emails", "how-to-negotiate-salary"],
    published: true },
  { slug: "how-to-get-promoted", type: "article", category: "career",
    title: "How to Get Promoted — Do the Next Job First",
    h1: "How to Get Promoted",
    description: "Get promoted by quietly doing the next role for 3 months before asking. Scripts and examples.",
    keyword: "how to get promoted",
    related: ["how-to-negotiate-salary", "how-to-network-effectively", "how-to-increase-your-income"],
    published: true },
  { slug: "how-to-deal-with-a-bad-boss", type: "article", category: "career",
    title: "How to Deal With a Bad Boss",
    h1: "How to Deal With a Bad Boss",
    description: "Manage up, document what matters, protect your time. When to stay and when it's time to leave.",
    keyword: "how to deal with a bad boss",
    related: ["how-to-set-boundaries", "how-to-quit-your-job-professionally", "how-to-beat-burnout"],
    published: true },
  { slug: "how-to-work-remotely", type: "article", category: "career",
    title: "How to Work Remotely — A Playbook",
    h1: "How to Work Remotely",
    description: "Remote work done right: over-communicate, async by default, and keep your calendar honest.",
    keyword: "how to work remotely",
    related: ["how-to-work-from-home-productively", "how-to-set-up-a-home-office", "time-zone-converter"],
    published: true },
  { slug: "how-to-switch-careers", type: "article", category: "career",
    title: "How to Switch Careers — Without Starting Over",
    h1: "How to Switch Careers",
    description: "Change careers without resetting your life: identify transferable skills, build proof, tell the story.",
    keyword: "how to switch careers",
    related: ["how-to-get-your-first-developer-job", "how-to-increase-your-income", "how-to-write-a-resume"],
    published: true },
  { slug: "best-linkedin-profile-tips", type: "article", category: "career",
    title: "Best LinkedIn Profile Tips for 2026",
    h1: "LinkedIn Profile Tips",
    description: "A LinkedIn profile recruiters actually click: headline, about, experience bullets, and photo.",
    keyword: "best LinkedIn profile tips",
    related: ["how-to-write-a-resume", "how-to-network-effectively", "how-to-switch-careers"],
    published: true },
  { slug: "how-to-give-a-great-presentation", type: "article", category: "career",
    title: "How to Give a Great Presentation",
    h1: "How to Give a Great Presentation",
    description: "Presentations that land: one big idea, three supports, a strong open and close.",
    keyword: "how to give a great presentation",
    related: ["how-to-write-professional-emails", "meeting-cost-calculator", "how-to-ace-a-job-interview"],
    published: true },
  { slug: "how-to-write-professional-emails", type: "article", category: "career",
    title: "How to Write Professional Emails (Templates Inside)",
    h1: "How to Write Professional Emails",
    description: "Write emails that get read and replied to. Subject, opening, ask, CTA. Templates for common situations.",
    keyword: "how to write professional emails",
    related: ["how-to-write-better", "how-to-give-a-great-presentation", "how-to-work-remotely"],
    published: true },

  // -------------------- ARTICLES: HOME (10) --------------------
  { slug: "how-to-declutter-your-home", type: "article", category: "home",
    title: "How to Declutter Your Home — A Room-by-Room Plan",
    h1: "How to Declutter Your Home",
    description: "Declutter without burning out: one room, one box, one rule. A realistic weekend plan.",
    keyword: "how to declutter your home",
    related: ["how-to-meal-prep", "how-to-build-good-habits", "countdown-timer"],
    published: true },
  { slug: "how-to-organize-your-digital-life", type: "article", category: "home",
    title: "How to Organize Your Digital Life",
    h1: "How to Organize Your Digital Life",
    description: "Inbox zero, clean desktop, backed-up files. A 2-hour reset plus habits to keep it that way.",
    keyword: "how to organize your digital life",
    related: ["password-generator", "how-to-declutter-your-home", "how-to-reduce-screen-time"],
    published: true },
  { slug: "how-to-cook-on-a-budget", type: "article", category: "home",
    title: "How to Cook on a Budget",
    h1: "How to Cook on a Budget",
    description: "Cook for less: staples, pantry meals, and the three recipes that stretch further than the others.",
    keyword: "how to cook on a budget",
    related: ["how-to-meal-prep", "how-to-save-on-groceries", "how-to-eat-healthy-on-a-budget"],
    published: true },
  { slug: "how-to-meal-prep", type: "article", category: "home",
    title: "How to Meal Prep — A Sunday System",
    h1: "How to Meal Prep",
    description: "A 2-hour Sunday meal prep that handles 5 weekday lunches. Shopping list, containers, and reheating.",
    keyword: "how to meal prep",
    related: ["how-to-save-on-groceries", "calorie-calculator", "how-to-declutter-your-home"],
    published: true },
  { slug: "how-to-clean-efficiently", type: "article", category: "home",
    title: "How to Clean Efficiently — Top-Down, In-Out",
    h1: "How to Clean Efficiently",
    description: "A clean-the-house-in-an-hour system: top-down, in-out, one cloth per room, finish strong.",
    keyword: "how to clean efficiently",
    related: ["how-to-declutter-your-home", "how-to-organize-your-digital-life", "how-to-save-on-utilities"],
    published: true },
  { slug: "how-to-plan-a-move", type: "article", category: "home",
    title: "How to Plan a Move — 8-Week Checklist",
    h1: "How to Plan a Move",
    description: "An 8-week moving checklist that prevents the 'what did we forget' panic at 9 p.m. the night before.",
    keyword: "how to plan a move",
    related: ["how-to-declutter-your-home", "how-to-pack-for-travel", "how-to-save-on-utilities"],
    published: true },
  { slug: "how-to-reduce-screen-time", type: "article", category: "home",
    title: "How to Reduce Screen Time — Realistically",
    h1: "How to Reduce Screen Time",
    description: "Cut phone use without deleting apps: friction first, replacement second, and a weekly audit.",
    keyword: "how to reduce screen time",
    related: ["how-to-organize-your-digital-life", "how-to-focus-better", "how-to-build-good-habits"],
    published: true },
  { slug: "how-to-pack-for-travel", type: "article", category: "home",
    title: "How to Pack for Travel — Carry-On Only",
    h1: "How to Pack for Travel",
    description: "Pack for a week in a carry-on: the capsule list, the 3-1-1 liquids rule, and what to leave at home.",
    keyword: "how to pack for travel",
    related: ["currency-converter", "how-to-plan-a-move", "how-to-save-money-fast"],
    published: true },
  { slug: "how-to-save-on-utilities", type: "article", category: "home",
    title: "How to Save on Utilities — Real Savings",
    h1: "How to Save on Utilities",
    description: "Lower your utility bills with high-leverage moves: thermostat, water heater, LEDs, and air sealing.",
    keyword: "how to save on utilities",
    related: ["how-to-save-money-fast", "budget-calculator", "how-to-live-below-your-means"],
    published: true },
  { slug: "how-to-set-up-a-home-office", type: "article", category: "home",
    title: "How to Set Up a Home Office — Under $500",
    h1: "How to Set Up a Home Office",
    description: "Set up a home office that works your body and your focus. Prioritized gear list under $500.",
    keyword: "how to set up a home office",
    related: ["how-to-work-from-home-productively", "how-to-fix-posture", "how-to-work-remotely"],
    published: true },

  // -------------------- ARTICLES: SOCIAL (5) --------------------
  { slug: "how-to-make-friends-as-an-adult", type: "article", category: "social",
    title: "How to Make Friends as an Adult",
    h1: "How to Make Friends as an Adult",
    description: "Make friends as an adult with the 3-3-3 rule: same people, recurring events, realistic timelines.",
    keyword: "how to make friends as an adult",
    related: ["how-to-have-better-conversations", "how-to-overcome-social-anxiety", "how-to-network-effectively"],
    published: true },
  { slug: "how-to-have-better-conversations", type: "article", category: "social",
    title: "How to Have Better Conversations",
    h1: "How to Have Better Conversations",
    description: "Better conversations in five moves: listen, ask one deeper, avoid the topic-switch, close well.",
    keyword: "how to have better conversations",
    related: ["how-to-make-friends-as-an-adult", "how-to-overcome-social-anxiety", "how-to-write-professional-emails"],
    published: true },
  { slug: "how-to-overcome-social-anxiety", type: "article", category: "social",
    title: "How to Overcome Social Anxiety — Small Exposures",
    h1: "How to Overcome Social Anxiety",
    description: "Beat social anxiety with graded exposure: small, repeated, uncomfortable-but-safe. A 6-week plan.",
    keyword: "how to overcome social anxiety",
    related: ["how-to-make-friends-as-an-adult", "how-to-have-better-conversations", "how-to-reduce-stress"],
    published: true },
  { slug: "how-to-set-boundaries", type: "article", category: "social",
    title: "How to Set Boundaries — Scripts and Follow-Through",
    h1: "How to Set Boundaries",
    description: "Set boundaries that stick: a short script, what to do when tested, and how to stop over-explaining.",
    keyword: "how to set boundaries",
    related: ["how-to-deal-with-a-bad-boss", "how-to-beat-burnout", "how-to-reduce-stress"],
    published: true },
  { slug: "how-to-apologize-well", type: "article", category: "social",
    title: "How to Apologize Well — Sincerely, Without 'But'",
    h1: "How to Apologize Well",
    description: "A real apology in 4 parts: name it, own it, repair it, commit to change. No 'but', no 'if'.",
    keyword: "how to apologize well",
    related: ["how-to-have-better-conversations", "how-to-set-boundaries", "how-to-write-professional-emails"],
    published: true },

  // -------------------- TOOLS: CONVERTERS (15) --------------------
  { slug: "color-converter", type: "tool", category: "converters",
    title: "Color Converter — HEX, RGB, HSL in One Tool",
    h1: "Color Converter",
    description: "Convert any color between HEX, RGB, and HSL. Paste a hex code or tweak channels and see every format update live.",
    keyword: "hex to rgb converter",
    related: ["number-base-converter", "svg-to-png", "image-format-converter"],
    published: true },
  { slug: "unix-timestamp-converter", type: "tool", category: "converters",
    title: "Unix Timestamp Converter — Epoch to Date, Both Ways",
    h1: "Unix Timestamp Converter",
    description: "Convert Unix epoch seconds or milliseconds to a human date, or a date to an epoch. Timezone-aware, runs offline.",
    keyword: "unix timestamp converter",
    related: ["time-zone-converter", "number-base-converter", "age-calculator"],
    published: true },
  { slug: "number-base-converter", type: "tool", category: "converters",
    title: "Number Base Converter — Binary, Decimal, Hex, Octal",
    h1: "Number Base Converter",
    description: "Convert any number between binary, octal, decimal, and hexadecimal at the same time. Clean UI, no ads.",
    keyword: "binary to decimal converter",
    related: ["color-converter", "unix-timestamp-converter", "base64-encoder-decoder"],
    published: true },
  { slug: "csv-to-json", type: "tool", category: "converters",
    title: "CSV to JSON Converter — Free, Runs in Browser",
    h1: "CSV to JSON",
    description: "Paste CSV rows and get clean JSON. Handles quoted fields, custom delimiters, and header-row toggling. No upload needed.",
    keyword: "csv to json",
    related: ["json-to-csv", "yaml-json-converter", "json-formatter"],
    published: true },
  { slug: "yaml-json-converter", type: "tool", category: "converters",
    title: "YAML to JSON Converter — Both Directions, Instant",
    h1: "YAML ↔ JSON Converter",
    description: "Convert YAML to JSON or JSON to YAML. Paste on one side, copy the other. Works for config files, data docs, and more.",
    keyword: "yaml to json",
    related: ["csv-to-json", "json-formatter", "xml-to-json"],
    published: true },
  { slug: "html-to-markdown", type: "tool", category: "converters",
    title: "HTML to Markdown Converter — Clean Output, Free",
    h1: "HTML to Markdown",
    description: "Paste HTML and get Markdown. Preserves headings, lists, links, code, and images. Great for migrating blogs and notes.",
    keyword: "html to markdown",
    related: ["markdown-to-html", "readability-score-checker", "word-counter"],
    published: true },
  { slug: "image-format-converter", type: "tool", category: "converters",
    title: "Image Format Converter — JPG, PNG, WebP",
    h1: "Image Format Converter",
    description: "Convert between JPG, PNG, and WebP in your browser. Nothing is uploaded. Ideal for quick format swaps before sharing.",
    keyword: "jpg to png converter",
    related: ["image-resizer", "image-compressor", "svg-to-png"],
    published: true },
  { slug: "image-resizer", type: "tool", category: "converters",
    title: "Image Resizer — Resize JPG, PNG, WebP Free",
    h1: "Image Resizer",
    description: "Resize images by pixels or percentage. Keeps aspect ratio by default, works offline, and never sends your photo anywhere.",
    keyword: "image resizer",
    related: ["image-compressor", "image-format-converter", "svg-to-png"],
    published: true },
  { slug: "image-compressor", type: "tool", category: "converters",
    title: "Image Compressor — Shrink JPG File Size in Browser",
    h1: "Image Compressor",
    description: "Drag in a JPG, drag a quality slider, and download a smaller file. Great for email, sites, and forms with upload limits.",
    keyword: "image compressor",
    related: ["image-resizer", "image-format-converter", "jpg-to-pdf"],
    published: true },
  { slug: "svg-to-png", type: "tool", category: "converters",
    title: "SVG to PNG Converter — Rasterize at Any Size",
    h1: "SVG to PNG",
    description: "Convert SVG to PNG at any resolution. Pick the output size, keep transparent background. 100% client-side.",
    keyword: "svg to png",
    related: ["image-format-converter", "image-resizer", "color-converter"],
    published: true },
  { slug: "pdf-to-text", type: "tool", category: "converters",
    title: "PDF to Text — Extract Plain Text Free",
    h1: "PDF to Text",
    description: "Drop a PDF and copy the plain text out. Works for reports, books, receipts. All processing happens in your browser.",
    keyword: "pdf to text",
    related: ["pdf-to-jpg", "merge-pdf", "word-counter"],
    published: true },
  { slug: "pdf-to-jpg", type: "tool", category: "converters",
    title: "PDF to JPG — Convert Each Page to an Image",
    h1: "PDF to JPG",
    description: "Render every page of a PDF as a JPG image you can save. No watermarks, no upload — runs fully in your browser.",
    keyword: "pdf to jpg",
    related: ["pdf-to-text", "jpg-to-pdf", "image-compressor"],
    published: true },
  { slug: "jpg-to-pdf", type: "tool", category: "converters",
    title: "JPG to PDF — Combine Images Into One PDF",
    h1: "JPG to PDF",
    description: "Select multiple images and combine them into a single PDF. Reorder, rotate, pick paper size. Everything stays local.",
    keyword: "jpg to pdf",
    related: ["pdf-to-jpg", "merge-pdf", "image-resizer"],
    published: true },
  { slug: "merge-pdf", type: "tool", category: "converters",
    title: "Merge PDF — Combine Multiple PDFs Online Free",
    h1: "Merge PDF",
    description: "Drop multiple PDFs, reorder them, and save a single combined file. No uploads, no accounts, no watermarks.",
    keyword: "merge pdf",
    related: ["pdf-to-text", "pdf-to-jpg", "jpg-to-pdf"],
    published: true },
  { slug: "heic-to-jpg", type: "tool", category: "converters",
    title: "HEIC to JPG Converter — iPhone Photos, Free",
    h1: "HEIC to JPG",
    description: "Convert iPhone HEIC photos to JPG right in your browser. Batch multiple files and download as JPGs. No uploads.",
    keyword: "heic to jpg",
    related: ["image-format-converter", "image-resizer", "image-compressor"],
    published: true },

  // -------------------- PARITY PASS: PDF TOOLS (8) --------------------
  { slug: "pdf-split", type: "tool", category: "converters",
    title: "Split PDF — Extract Pages or Break into Parts Free",
    h1: "Split PDF",
    description: "Split a PDF into individual pages or custom page ranges. All processing happens in your browser — no uploads, no watermarks.",
    keyword: "split pdf",
    related: ["merge-pdf", "pdf-organizer", "how-to-split-a-pdf"],
    published: true },
  { slug: "pdf-metadata-viewer", type: "tool", category: "converters",
    title: "PDF Metadata Viewer — Inspect Author, Dates, Producer",
    h1: "PDF Metadata Viewer",
    description: "See the hidden metadata in any PDF — title, author, producer, creation date, keywords. Runs fully offline in your browser.",
    keyword: "pdf metadata viewer",
    related: ["pdf-metadata-remover", "merge-pdf", "how-to-remove-pdf-metadata"],
    published: true },
  { slug: "pdf-metadata-remover", type: "tool", category: "converters",
    title: "PDF Metadata Remover — Strip Author & Hidden Info",
    h1: "PDF Metadata Remover",
    description: "Wipe author, title, producer, and other metadata from any PDF before sharing. Done locally — your file never leaves your browser.",
    keyword: "pdf metadata remover",
    related: ["pdf-metadata-viewer", "merge-pdf", "how-to-remove-pdf-metadata"],
    published: true },
  { slug: "pdf-to-long-image", type: "tool", category: "converters",
    title: "PDF to Long Image — Stitch All Pages into One PNG",
    h1: "PDF to Long Image",
    description: "Convert a PDF into a single tall image — every page stitched vertically. Great for mobile sharing and screenshots.",
    keyword: "pdf to long image",
    related: ["pdf-to-jpg", "pdf-to-text", "image-compressor"],
    published: true },
  { slug: "pdf-watermark", type: "tool", category: "converters",
    title: "PDF Watermark — Add Text Watermark to Every Page",
    h1: "PDF Watermark",
    description: "Stamp a text watermark across every page of a PDF. Pick position, opacity, color, rotation. All in your browser, no uploads.",
    keyword: "pdf watermark",
    related: ["pdf-page-numbers", "merge-pdf", "how-to-add-watermark-to-pdf"],
    published: true },
  { slug: "pdf-organizer", type: "tool", category: "converters",
    title: "PDF Organizer — Reorder, Delete, Rotate PDF Pages",
    h1: "PDF Organizer",
    description: "Reorder, rotate, and delete pages in a PDF visually. Nothing uploaded — your file is processed entirely in your browser.",
    keyword: "pdf organizer",
    related: ["pdf-split", "merge-pdf", "pdf-page-numbers"],
    published: true },
  { slug: "pdf-page-numbers", type: "tool", category: "converters",
    title: "PDF Page Numbers — Add Numbering to Every Page",
    h1: "PDF Page Numbers",
    description: "Add page numbers to any PDF. Pick position, font size, starting number, format. 100% local, no account needed.",
    keyword: "pdf page numbers",
    related: ["pdf-watermark", "pdf-organizer", "how-to-add-page-numbers-to-pdf"],
    published: true },
  { slug: "pdf-crop", type: "tool", category: "converters",
    title: "PDF Crop — Trim Margins from Every Page Free",
    h1: "PDF Crop",
    description: "Crop margins off every page of a PDF in one click. Ideal for cleaning up scans. Runs entirely in your browser.",
    keyword: "pdf crop",
    related: ["pdf-organizer", "pdf-split", "merge-pdf"],
    published: true },

  // -------------------- PARITY PASS: IMAGE TOOLS (4) --------------------
  { slug: "webp-to-jpg", type: "tool", category: "converters",
    title: "WebP to JPG — Convert WebP Images to JPG Free",
    h1: "WebP to JPG",
    description: "Convert WebP images to JPG instantly. Batch many files at once, pick quality, download — all done in your browser.",
    keyword: "webp to jpg",
    related: ["image-format-converter", "image-compressor", "how-to-convert-webp-to-jpg"],
    published: true },
  { slug: "image-cropper", type: "tool", category: "converters",
    title: "Image Cropper — Crop Photos Online Free",
    h1: "Image Cropper",
    description: "Crop any image to a custom box, square, or fixed aspect ratio. Works on JPG, PNG, WebP — offline, no watermarks.",
    keyword: "image cropper",
    related: ["image-resizer", "image-compressor", "how-to-crop-images-online"],
    published: true },
  { slug: "color-extractor", type: "tool", category: "converters",
    title: "Color Extractor — Pull a Palette From Any Image",
    h1: "Color Extractor",
    description: "Upload an image and extract its dominant colors as a palette. HEX, RGB, HSL — copy one click. All in your browser.",
    keyword: "color extractor",
    related: ["color-converter", "image-resizer", "how-to-extract-colors-from-an-image"],
    published: true },
  { slug: "gif-maker", type: "tool", category: "converters",
    title: "GIF Maker — Build Animated GIFs from Images Free",
    h1: "GIF Maker",
    description: "Turn a stack of images into a smooth animated GIF. Set frame delay, loop, and size. 100% in-browser, no uploads.",
    keyword: "gif maker",
    related: ["image-resizer", "image-compressor", "how-to-create-gifs-from-images"],
    published: true },

  // -------------------- PARITY PASS: UTILITY + DEV (8) --------------------
  { slug: "qr-code-generator", type: "tool", category: "dev",
    title: "QR Code Generator — Free, High-Quality, No Login",
    h1: "QR Code Generator",
    description: "Generate QR codes for URLs, text, wifi, or email. Customize size and error level. Download PNG or SVG — free and offline.",
    keyword: "qr code generator",
    related: ["password-generator", "uuid-generator", "how-to-generate-qr-codes"],
    published: true },
  { slug: "age-gap-calculator", type: "tool", category: "random",
    title: "Age Gap Calculator — Compare Ages in Years, Months, Days",
    h1: "Age Gap Calculator",
    description: "Enter two birthdays — see the age gap in years, months, and days. Works for couples, siblings, or any two people.",
    keyword: "age gap calculator",
    related: ["age-calculator", "percentage-calculator", "how-to-calculate-age-gap"],
    published: true },
  { slug: "percentage-calculator", type: "tool", category: "money",
    title: "Percentage Calculator — Quick % of, % Change, % More",
    h1: "Percentage Calculator",
    description: "Calculate percent of a number, percent change, and add/subtract a percent. Fast, clean, and mobile-friendly.",
    keyword: "percentage calculator",
    related: ["tip-calculator", "loan-calculator", "how-to-calculate-percentages"],
    published: true },
  { slug: "hash-generator", type: "tool", category: "dev",
    title: "Hash Generator — MD5, SHA-1, SHA-256, SHA-512 Free",
    h1: "Hash Generator",
    description: "Generate MD5, SHA-1, SHA-256, and SHA-512 hashes from any text or file. Client-side — your input never leaves the browser.",
    keyword: "hash generator",
    related: ["password-generator", "password-breach-checker", "how-to-hash-passwords"],
    published: true },
  { slug: "css-minifier", type: "tool", category: "dev",
    title: "CSS Minifier — Shrink Stylesheets Online Free",
    h1: "CSS Minifier",
    description: "Paste CSS, strip comments and whitespace, and get a smaller minified version. Offline, safe, no ads or sign-ups.",
    keyword: "css minifier",
    related: ["js-minifier", "json-formatter", "xml-formatter"],
    published: true },
  { slug: "js-minifier", type: "tool", category: "dev",
    title: "JavaScript Minifier — Compress JS Code Online",
    h1: "JavaScript Minifier",
    description: "Paste JavaScript and shrink it by stripping comments and whitespace. A fast, safe in-browser minifier — no accounts.",
    keyword: "javascript minifier",
    related: ["css-minifier", "json-formatter", "xml-formatter"],
    published: true },
  { slug: "xml-formatter", type: "tool", category: "dev",
    title: "XML Formatter — Beautify & Validate XML Online Free",
    h1: "XML Formatter",
    description: "Paste XML — get a clean, indented version plus a syntax check. Runs entirely in your browser, no uploads.",
    keyword: "xml formatter",
    related: ["json-formatter", "yaml-json-converter", "css-minifier"],
    published: true },
  { slug: "diff-checker", type: "tool", category: "dev",
    title: "Diff Checker — Compare Two Texts Side by Side",
    h1: "Diff Checker",
    description: "Paste two blocks of text and see what changed line-by-line. Great for contracts, code, and writing revisions.",
    keyword: "diff checker",
    related: ["json-formatter", "regex-tester", "character-counter"],
    published: true },

  // -------------------- PARITY PASS: GUIDES (15) --------------------
  { slug: "how-to-merge-pdfs", type: "article", category: "converters",
    title: "How to Merge PDFs — Quick, Free, Offline Method",
    h1: "How to merge PDFs",
    description: "A simple, privacy-safe way to merge PDFs right in your browser. No watermarks, no sign-up, no upload. Takes under a minute.",
    keyword: "how to merge pdfs",
    related: ["merge-pdf", "pdf-split", "how-to-split-a-pdf"],
    published: true },
  { slug: "how-to-split-a-pdf", type: "article", category: "converters",
    title: "How to Split a PDF — Extract Pages or Ranges Free",
    h1: "How to split a PDF",
    description: "Split a PDF by pages or ranges without uploading to a server. Clear steps, common pitfalls, and a free in-browser tool.",
    keyword: "how to split a pdf",
    related: ["pdf-split", "merge-pdf", "pdf-organizer"],
    published: true },
  { slug: "how-to-compress-images-without-losing-quality", type: "article", category: "converters",
    title: "How to Compress Images Without Losing Quality",
    h1: "How to compress images without losing quality",
    description: "Pick the right format, dimensions, and quality knobs to shrink image size while keeping photos sharp. Plain steps, real numbers.",
    keyword: "how to compress images",
    related: ["image-compressor", "image-resizer", "image-format-converter"],
    published: true },
  { slug: "how-to-generate-qr-codes", type: "article", category: "dev",
    title: "How to Generate QR Codes — Clear Steps for Any Link",
    h1: "How to generate QR codes",
    description: "Make a QR code for a URL, wifi, vCard, or plain text. What error-correction means, how big to print, how to test it.",
    keyword: "how to generate qr codes",
    related: ["qr-code-generator", "password-generator", "uuid-generator"],
    published: true },
  { slug: "how-to-calculate-age-gap", type: "article", category: "random",
    title: "How to Calculate an Age Gap in Years, Months, Days",
    h1: "How to calculate an age gap",
    description: "A step-by-step method — and a free calculator — for finding the exact age gap between two people in years, months, and days.",
    keyword: "how to calculate age gap",
    related: ["age-gap-calculator", "age-calculator", "percentage-calculator"],
    published: true },
  { slug: "how-to-calculate-percentages", type: "article", category: "money",
    title: "How to Calculate Percentages — 5 Everyday Formulas",
    h1: "How to calculate percentages",
    description: "Percent of a number, percent change, percent off, markup, tip — the five most useful percentage formulas, with examples.",
    keyword: "how to calculate percentages",
    related: ["percentage-calculator", "tip-calculator", "loan-calculator"],
    published: true },
  { slug: "how-to-convert-webp-to-jpg", type: "article", category: "converters",
    title: "How to Convert WebP to JPG — Free, In Your Browser",
    h1: "How to convert WebP to JPG",
    description: "Turn WebP images into universally compatible JPGs in seconds. Why WebP exists, when JPG is better, and a free converter.",
    keyword: "how to convert webp to jpg",
    related: ["webp-to-jpg", "image-format-converter", "image-compressor"],
    published: true },
  { slug: "how-to-crop-images-online", type: "article", category: "converters",
    title: "How to Crop Images Online — Free, No Watermark",
    h1: "How to crop images online",
    description: "Pick an aspect ratio, drag a crop box, and export — all without installing Photoshop. Tips for profile pics and social posts.",
    keyword: "how to crop images online",
    related: ["image-cropper", "image-resizer", "image-format-converter"],
    published: true },
  { slug: "how-to-extract-colors-from-an-image", type: "article", category: "converters",
    title: "How to Extract Colors From an Image — Free Palette Tool",
    h1: "How to extract colors from an image",
    description: "Pull the dominant colors out of any photo and copy HEX, RGB, or HSL. Great for branding, mood boards, and design work.",
    keyword: "how to extract colors from an image",
    related: ["color-extractor", "color-converter", "image-format-converter"],
    published: true },
  { slug: "how-to-create-gifs-from-images", type: "article", category: "converters",
    title: "How to Create GIFs From Images — Free, Offline Steps",
    h1: "How to create GIFs from images",
    description: "Build a smooth animated GIF from a stack of PNGs or JPGs. Frame timing, looping, size tradeoffs — in plain English.",
    keyword: "how to create gifs from images",
    related: ["gif-maker", "image-resizer", "image-compressor"],
    published: true },
  { slug: "how-to-add-watermark-to-pdf", type: "article", category: "converters",
    title: "How to Add a Watermark to a PDF — Free, No Sign-up",
    h1: "How to add a watermark to a PDF",
    description: "Stamp a text watermark across every page of a PDF. When to use DRAFT vs CONFIDENTIAL, opacity tips, and a free tool.",
    keyword: "how to add a watermark to a pdf",
    related: ["pdf-watermark", "pdf-page-numbers", "merge-pdf"],
    published: true },
  { slug: "how-to-add-page-numbers-to-pdf", type: "article", category: "converters",
    title: "How to Add Page Numbers to a PDF — Simple Steps",
    h1: "How to add page numbers to a PDF",
    description: "Add page numbers to any PDF — pick position, size, format. Why booklets need different numbering than contracts.",
    keyword: "how to add page numbers to a pdf",
    related: ["pdf-page-numbers", "pdf-watermark", "pdf-organizer"],
    published: true },
  { slug: "how-to-remove-pdf-metadata", type: "article", category: "converters",
    title: "How to Remove Metadata from a PDF — Privacy Checklist",
    h1: "How to remove metadata from a PDF",
    description: "PDFs carry author names, timestamps, and software traces you may not want to share. How to find it — and how to strip it.",
    keyword: "how to remove pdf metadata",
    related: ["pdf-metadata-remover", "pdf-metadata-viewer", "merge-pdf"],
    published: true },
  { slug: "how-to-hash-passwords", type: "article", category: "coding",
    title: "How to Hash Passwords — What bcrypt, Argon2 Really Do",
    h1: "How to hash passwords",
    description: "Why you never store plain passwords, why MD5/SHA-1 aren't enough for auth, and how bcrypt/Argon2 actually protect users.",
    keyword: "how to hash passwords",
    related: ["hash-generator", "password-generator", "password-breach-checker"],
    published: true },
  { slug: "how-to-use-regex-effectively", type: "article", category: "coding",
    title: "How to Use Regex Effectively — A Practical Cheat Sheet",
    h1: "How to use regex effectively",
    description: "The handful of regex features that cover 90% of real work — anchors, classes, quantifiers, groups — with runnable examples.",
    keyword: "how to use regex",
    related: ["regex-tester", "diff-checker", "how-to-learn-coding-fast"],
    published: true },
];

// ---------- Helpers ----------

export const getPageBySlug = (slug: string): Page | undefined =>
  PAGES.find(p => p.slug === slug);

export const getPublishedPages = (): Page[] =>
  PAGES.filter(p => p.published);

export const getPublishedTools = (): Page[] =>
  PAGES.filter(p => p.published && p.type === "tool");

export const getPublishedGuides = (): Page[] =>
  PAGES.filter(p => p.published && p.type === "article");

export const getAllTools = (): Page[] =>
  PAGES.filter(p => p.type === "tool");

export const getAllGuides = (): Page[] =>
  PAGES.filter(p => p.type === "article");

export const getPublishedByCategory = (category: Category): Page[] =>
  PAGES.filter(p => p.published && p.category === category);

/**
 * Return 2-3 related *published* pages for a given page.
 * Tier 1: declared related slugs that are published.
 * Tier 2: other published pages in the same category.
 * Tier 3: any other published page (so we always surface 2-3, even when the
 *         cluster is still thin early on).
 */
export function getRelated(slug: string, limit = 3): Page[] {
  const page = getPageBySlug(slug);
  if (!page) return [];
  const result: Page[] = [];
  const push = (p: Page) => {
    if (p.slug === slug) return;
    if (!p.published) return;
    if (result.find(r => r.slug === p.slug)) return;
    result.push(p);
  };

  // Tier 1 — declared related, in the order the author wrote them.
  for (const s of page.related || []) {
    const p = getPageBySlug(s);
    if (p) push(p);
    if (result.length >= limit) return result.slice(0, limit);
  }

  // Tier 2 — same-category filler.
  for (const p of PAGES) {
    if (p.category === page.category) push(p);
    if (result.length >= limit) return result.slice(0, limit);
  }

  // Tier 3 — anything else published, so every page has at least a couple.
  for (const p of PAGES) {
    push(p);
    if (result.length >= limit) return result.slice(0, limit);
  }

  return result.slice(0, limit);
}

export function pageHref(page: Page): string {
  return page.type === "tool" ? `/tools/${page.slug}` : `/guides/${page.slug}`;
}
