// Wire Wave 2: 12 cooking + 12 parenting tools
import { readFileSync, writeFileSync } from "node:fs";

const tools = [
  // Cooking (12)
  ["baking-conversion-calculator", "BakingConversionCalculator", "Baking Conversion Calculator", "Cups to grams for flour, sugar, butter, and 16 baking staples. Metric + imperial side-by-side reference.", "baking conversion calculator", "cooking", ["sourdough-hydration-calculator", "pizza-dough-calculator", "bread-baker-percentages"], "US cups to grams, the right way &mdash; flour is 125g, not 120g, because the tool knows your ingredient. 16 common baking ingredients pre-loaded.", ["Pick ingredient.", "Enter amount + unit.", "Read all 6 equivalents."]],
  ["meat-doneness-temperature", "MeatDonenessTemperature", "Meat Doneness Temperature Guide", "USDA-safe internal temps for beef, pork, chicken, fish, lamb. Rest times included. Celsius + Fahrenheit.", "meat doneness temperature", "cooking", ["sous-vide-time-temp", "food-storage-shelf-life", "coffee-ratio-calculator"], "Safe temps for every meat, plus chef-preferred temps for rare and medium-rare. Rest times included because rested meat is better meat.", ["Pick meat type.", "Read doneness table.", "Add rest time before slicing."]],
  ["food-storage-shelf-life", "FoodStorageShelfLife", "Food Storage Shelf Life Calculator", "How long food lasts in fridge and freezer. 30+ foods with good-until dates from your purchase date.", "food storage shelf life", "cooking", ["meat-doneness-temperature", "baking-conversion-calculator", "rice-to-water-ratio"], "Sniff test isn&rsquo;t always reliable. Pick the food, enter the date you bought it, get fridge + freezer good-until dates plus storage tips.", ["Pick food type.", "Enter purchase date.", "Read good-until dates."]],
  ["sourdough-hydration-calculator", "SourdoughHydrationCalculator", "Sourdough Hydration Calculator", "Baker&rsquo;s hydration ratio with starter accounting. Tier-labeled from stiff to high-hydration.", "sourdough hydration", "cooking", ["bread-baker-percentages", "pizza-dough-calculator", "baking-conversion-calculator"], "Hydration math minus the sourdough-forum confusion. Accounts for starter water content so your 70% really is 70%.", ["Enter flour, water, starter.", "Read total hydration %.", "Compare to tier."]],
  ["coffee-ratio-calculator", "CoffeeRatioCalculator", "Coffee Ratio Calculator", "Coffee-to-water ratios for drip, french press, espresso, aeropress, pour-over, cold brew. Grams + tbsp.", "coffee ratio calculator", "cooking", ["cocktail-ratio-guide", "meat-doneness-temperature", "baking-conversion-calculator"], "1:16 for drip, 1:15 for french press, 1:2 for espresso. This picks the ratio for your method and tells you grams of beans to grind.", ["Pick brew method.", "Enter cups desired.", "Read coffee + water."]],
  ["cocktail-ratio-guide", "CocktailRatioGuide", "Cocktail Ratio Guide", "Classic cocktail ratios for 15 drinks. Scaled to any serving count, oz + ml.", "cocktail ratio guide", "cooking", ["coffee-ratio-calculator", "grocery-budget-splitter", "baking-conversion-calculator"], "Old Fashioned is 2:0.25:2 dash. Martini is 6:1. Negroni is 1:1:1. 15 classics with the ratios that actually taste right, scaled to your guest count.", ["Pick a cocktail.", "Set servings.", "Read ingredient amounts."]],
  ["sous-vide-time-temp", "SousVideTimeTemp", "Sous Vide Time and Temperature Guide", "Temperature + time table for 9 proteins and doneness levels. Includes pasteurization safety note.", "sous vide time temp", "cooking", ["meat-doneness-temperature", "food-storage-shelf-life", "rice-to-water-ratio"], "Beef steak at 129&deg;F for 2 hours is medium-rare nirvana. 9 proteins, every doneness level, with safety temps called out.", ["Pick protein.", "Pick doneness.", "Read temp + time range."]],
  ["pizza-dough-calculator", "PizzaDoughCalculator", "Pizza Dough Calculator", "Scale pizza dough recipe by baker&rsquo;s percentages. Hydration, salt, yeast, oil all adjustable.", "pizza dough calculator", "cooking", ["sourdough-hydration-calculator", "bread-baker-percentages", "baking-conversion-calculator"], "Neapolitan, NY, or Detroit &mdash; scale dough by the number of pizzas. 65% hydration, 2% salt, 0.3% yeast. Adjust to taste.", ["Pick pizza count and size.", "Set hydration and extras.", "Read ingredient grams."]],
  ["rice-to-water-ratio", "RiceToWaterRatio", "Rice to Water Ratio", "Perfect rice-to-water ratios for 8 rice types. Cups + ml + cook times. Stovetop vs rice cooker.", "rice to water ratio", "cooking", ["baking-conversion-calculator", "meat-doneness-temperature", "sous-vide-time-temp"], "White long-grain 1:2. Brown 1:2.5. Basmati 1:1.75. 8 rice types, the right water for each, plus stovetop vs cooker times.", ["Pick rice type.", "Enter cups.", "Read water + cook time."]],
  ["grocery-budget-splitter", "GroceryBudgetSplitter", "Grocery Budget Splitter", "Split a shared grocery bill fairly. Per-item allocation (all/shared/person-only). Per-person totals.", "grocery budget splitter", "cooking", ["bill-split-calculator", "expense-split-calculator", "rent-split-calculator"], "Roommate grocery shopping without awkward Venmo requests. Mark which items go to whom &mdash; all shared, shared-with-some, or person-only &mdash; totals update live.", ["Add people (2-6).", "Add items + allocations.", "Read per-person totals."]],
  ["bread-baker-percentages", "BreadBakerPercentages", "Bread Baker&rsquo;s Percentages Calculator", "Convert any bread recipe to baker&rsquo;s percentages. Scale to any new flour weight instantly.", "bread baker percentages", "cooking", ["sourdough-hydration-calculator", "pizza-dough-calculator", "baking-conversion-calculator"], "Baker&rsquo;s math: flour is 100%, everything else is a percent of flour. Paste any recipe, get the percentages, scale to any new flour weight in one click.", ["Enter flour + other ingredients.", "Read percentages.", "Scale to new flour weight."]],
  ["ice-cream-scoop-calculator", "IceCreamScoopCalculator", "Ice Cream Scoop Calculator", "How much ice cream for a party. Kids half-portion, flavor split, cost estimate at $7/quart.", "ice cream scoop calculator", "cooking", ["grocery-budget-splitter", "cocktail-ratio-guide", "coffee-ratio-calculator"], "Don&rsquo;t run out at the barbecue. Adults + kids + scoops = total gallons, flavor breakdown, and a cost estimate.", ["Enter guest count and scoop size.", "Pick flavor count.", "Read gallons + cost."]],

  // Parenting (12)
  ["baby-sleep-schedule-builder", "BabySleepScheduleBuilder", "Baby Sleep Schedule Builder", "Age-appropriate sleep totals, nap counts, and wake windows from newborn through 24 months. Sample daily schedule.", "baby sleep schedule", "parenting", ["baby-formula-mixing-calculator", "baby-bottle-feeding-amount", "baby-weight-percentile"], "Wake windows and nap counts that match your baby&rsquo;s age. Sample schedule included so you can start tonight.", ["Enter baby age in months.", "Read sleep totals + naps.", "Use the sample schedule."]],
  ["baby-formula-mixing-calculator", "BabyFormulaMixingCalculator", "Baby Formula Mixing Calculator", "Correct formula-to-water ratios for powder, concentrate, or ready-to-feed. Storage rules.", "baby formula mixing", "parenting", ["baby-bottle-feeding-amount", "baby-sleep-schedule-builder", "baby-food-portion-guide"], "Never dilute formula &mdash; water intoxication is a real risk. Correct ratios for all three types, plus storage rules.", ["Pick formula type.", "Enter ounces desired.", "Read scoop + water amount."]],
  ["diaper-count-estimator", "DiaperCountEstimator", "Diaper Count Estimator", "Diapers per day, month, and year by age. Cost per month, size progression, cloth comparison.", "diaper count estimator", "parenting", ["baby-sleep-schedule-builder", "baby-formula-mixing-calculator", "daycare-cost-calculator"], "You&rsquo;ll go through ~2,700 diapers in year one. Plan the budget, the size progression, and whether cloth saves you money long-term.", ["Pick baby age band.", "Enter cost per diaper.", "Read monthly + yearly."]],
  ["baby-weight-percentile", "BabyWeightPercentile", "Baby Weight Percentile Calculator", "WHO/CDC growth chart percentile from age, sex, and weight. 0-36 months.", "baby weight percentile", "parenting", ["baby-sleep-schedule-builder", "baby-food-portion-guide", "child-height-prediction"], "WHO and CDC percentiles without a clinic visit. Track the trend &mdash; a single reading means nothing; the curve means everything.", ["Enter baby age, sex, weight.", "Read percentile.", "Track with pediatrician."]],
  ["baby-food-portion-guide", "BabyFoodPortionGuide", "Baby Food Portion Guide", "How much solid food to offer by age. Per-meal portions, allergen intro list, foods to wait on.", "baby food portion guide", "parenting", ["baby-bottle-feeding-amount", "baby-formula-mixing-calculator", "baby-weight-percentile"], "6-8 months is starter portions. 9-11 is expanding. 12+ is variety. Portion guidance for each food group, plus allergen intro and wait-list.", ["Pick baby age band.", "Read per-food portions.", "Review allergen + wait list."]],
  ["child-screen-time-tracker", "ChildScreenTimeTracker", "Child Screen Time Tracker", "AAP-aligned screen time targets by age. Gap-to-target calc and activity-swap ideas.", "child screen time tracker", "parenting", ["toddler-tantrum-calculator", "allowance-age-calculator", "child-height-prediction"], "AAP recommends no screen under 2 and max 1 hour daily age 2-5. This shows the gap and suggests swaps &mdash; not guilt-trips.", ["Pick child age band.", "Enter current daily screen time.", "Read tier + swap ideas."]],
  ["allowance-age-calculator", "AllowanceAgeCalculator", "Allowance by Age Calculator", "Age-appropriate weekly allowance. 5-currency support. Save/spend/give split suggestions.", "allowance by age", "parenting", ["child-screen-time-tracker", "daycare-cost-calculator", "toddler-tantrum-calculator"], "$1-$2 per week per year of age is a solid US baseline. With save/spend/give splits that teach money skills from age 5.", ["Enter child age + region.", "Pick chores-based or unconditional.", "Read weekly/monthly/yearly."]],
  ["toddler-tantrum-calculator", "ToddlerTantrumCalculator", "Toddler Tantrum Tracker", "Typical tantrum frequency by age (peaks 2-3 years). Triggers, de-escalation tips, reassurance.", "toddler tantrum tracker", "parenting", ["child-screen-time-tracker", "baby-sleep-schedule-builder", "child-height-prediction"], "Tantrums peak at 2-3 years with 2-5 per day being normal. Trigger checklist + de-escalation list + reassurance that this is a milestone, not a problem.", ["Enter toddler age.", "Check triggers.", "Read typical range + tips."]],
  ["child-height-prediction", "ChildHeightPrediction", "Child Adult Height Prediction", "Mid-parental height formula with ±4 inch range. Growth curve projection too.", "child adult height prediction", "parenting", ["baby-weight-percentile", "child-screen-time-tracker", "allowance-age-calculator"], "Mid-parental formula predicts adult height within ±4 inches for 95% of kids. Genetics is 80%. The rest is sleep, nutrition, and health.", ["Enter parents&rsquo; heights.", "Enter child age + current height.", "Read predicted adult height."]],
  ["daycare-cost-calculator", "DaycareCostCalculator", "Daycare Cost Calculator", "Weekly, monthly, annual daycare cost by location, type, and age. Infant center to in-home nanny.", "daycare cost calculator", "parenting", ["diaper-count-estimator", "allowance-age-calculator", "baby-sleep-schedule-builder"], "Childcare costs a new-car payment per year. Compare center vs home daycare vs nanny across four US location tiers and three age groups.", ["Pick location + type.", "Pick child age.", "Read weekly/monthly/annual."]],
  ["breastfeeding-duration-tracker", "BreastfeedingDurationTracker", "Breastfeeding Duration Tracker", "Log nursing sessions, see daily totals, compare against typical ranges for baby age.", "breastfeeding duration tracker", "parenting", ["baby-formula-mixing-calculator", "baby-sleep-schedule-builder", "baby-bottle-feeding-amount"], "Track duration and side, see daily totals and averages, and compare against typical ranges by age. Baby getting enough is measured by weight gain and diapers &mdash; not the clock.", ["Log each session.", "Read running total + average.", "Compare to age-typical range."]],
  ["baby-bottle-feeding-amount", "BabyBottleFeedingAmount", "Baby Bottle Feeding Amount Calculator", "How many ounces per bottle and per day by age and weight. 2.5 oz/lb rule with 32 oz/day cap.", "baby bottle feeding amount", "parenting", ["baby-formula-mixing-calculator", "baby-sleep-schedule-builder", "baby-food-portion-guide"], "2.5 oz formula per pound of body weight per day, up to 32 oz max. With age-appropriate bottles-per-day and a hunger-cue reminder.", ["Enter baby age + weight.", "Read oz per day.", "See bottles-per-day suggestion."]],
];

let toolSrc = readFileSync("components/tools/registry.tsx", "utf8");
const toolImports = tools.map(([, cls]) => `const ${cls} = dynamic(() => import("./${cls}").then(m => ({ default: m.${cls} })), { loading: Skeleton });`).join("\n");
const registryAnchor = `export const TOOL_REGISTRY: Record<string, ToolEntry> = {`;
toolSrc = toolSrc.replace(registryAnchor, `// Wave 2 cooking + parenting (24 new)\n${toolImports}\n\n${registryAnchor}`);
const lastRegEnd = toolSrc.lastIndexOf("};");
const toolEntries = tools.map(([slug, cls, , , , , , explainer, howToUse]) => {
  const howToStr = howToUse.map((s) => `      "${s.replace(/"/g, '\\"')}",`).join("\n");
  return `  "${slug}": {\n    render: () => <${cls} />,\n    explainer: (\n      <>\n        <p>${explainer}</p>\n        <p>\n          Runs entirely in your browser — no upload, no account, no watermark.\n          For more tools in this category see the{" "}\n          <a href="/tools">full tools index</a>.\n        </p>\n      </>\n    ),\n    howToUse: [\n${howToStr}\n    ],\n  },`;
}).join("\n");
toolSrc = toolSrc.slice(0, lastRegEnd) + toolEntries + "\n" + toolSrc.slice(lastRegEnd);
writeFileSync("components/tools/registry.tsx", toolSrc);
console.log("registry patched:", tools.length);

let pages = readFileSync("lib/pages.ts", "utf8");
const marker = "export const PAGES: Page[] = [";
const markerStart = pages.indexOf(marker);
const openBracket = markerStart + marker.length - 1;
let depth = 1, i = openBracket + 1, inStr = false, q = "", esc = false;
while (i < pages.length && depth > 0) {
  const c = pages[i];
  if (inStr) { if (esc) esc = false; else if (c === "\\") esc = true; else if (c === q) inStr = false; }
  else if (c === '"' || c === "'" || c === "`") { inStr = true; q = c; }
  else if (c === "[") depth++;
  else if (c === "]") depth--;
  i++;
}
const closeBracket = i - 1;
const esc2 = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const manifestEntries = tools.map(([slug, , title, description, keyword, category, related]) => {
  const relatedArr = related.map((s) => `"${s}"`).join(", ");
  return `  { slug: "${slug}", type: "tool", category: "${category}",\n    title: "${esc2(title)}",\n    h1: "${esc2(title)}",\n    description: "${esc2(description)}",\n    keyword: "${keyword}",\n    related: [${relatedArr}],\n    published: true },`;
}).join("\n");
pages = pages.slice(0, closeBracket) + "\n" + manifestEntries + "\n" + pages.slice(closeBracket);
writeFileSync("lib/pages.ts", pages);
console.log("manifest patched:", tools.length);
