// Wire Wave 3: 12 education + 10 events
import { readFileSync, writeFileSync } from "node:fs";

const tools = [
  // Education (12) — career for academic planning, writing for citation
  ["citation-generator", "CitationGenerator", "Citation Generator", "APA 7, MLA 9, Chicago 17, Harvard citations for books, journals, websites, newspapers. In-text + full citation.", "citation generator", "writing", ["act-to-sat-converter", "research-paper-reading-time", "cefr-language-level-test"], "Format citations in the 4 styles profs actually assign. Book, journal, website, newspaper &mdash; both in-text and full reference.", ["Pick style and source type.", "Fill author/year/title.", "Copy formatted citation."]],
  ["act-to-sat-converter", "ActToSatConverter", "ACT to SAT Converter", "Official ACT-SAT concordance conversion with percentile ranks. Both directions, full score range.", "act to sat converter", "career", ["test-score-percentile-lookup", "college-affordability-calculator", "college-gpa-projector"], "Official concordance table &mdash; ACT 30 maps to SAT 1360-1390. Percentile ranks for both tests so you know where you stand.", ["Pick source test.", "Enter score.", "Read equivalent score + percentile."]],
  ["college-gpa-projector", "CollegeGpaProjector", "College GPA Projector", "Projects your final GPA from current credits + target. Shows required semester GPA for any target.", "college gpa projector", "career", ["semester-gpa-target-calculator", "final-exam-grade-needed", "act-to-sat-converter"], "Plan the climb: current GPA, target GPA, and exactly what semester GPA you need to hit it. Graph included.", ["Enter current GPA + credits.", "Enter target + remaining credits.", "Read required semester GPA."]],
  ["semester-gpa-target-calculator", "SemesterGpaTargetCalculator", "Semester GPA Target Calculator", "What grades per class do you need? Dynamic class list, 3 allocation strategies.", "semester gpa target", "career", ["college-gpa-projector", "final-exam-grade-needed", "study-time-planner"], "3 classes at A, 1 at B+ gets you to 3.7? Enter your classes + credits, pick a target, see multiple valid grade combos.", ["Add classes + credits.", "Set target GPA.", "Pick strategy."]],
  ["study-time-planner", "StudyTimePlanner", "Study Time Planner", "Study hours needed for an exam by subject type, familiarity, and chapters. Pomodoro blocks + cramming warning.", "study time planner", "career", ["flashcard-study-estimator", "research-paper-reading-time", "semester-gpa-target-calculator"], "STEM 3-5 hrs/chapter, language 2-3, memorization 1-2. Familiarity adjusts the multiplier. Tells you daily hours and warns if you&rsquo;re cramming.", ["Pick subject type.", "Enter chapters + familiarity.", "Read daily study hours."]],
  ["final-exam-grade-needed", "FinalExamGradeNeeded", "Final Exam Grade Needed Calculator", "What score do you need on the final to hit your target course grade? Alt-targets table.", "final exam grade needed", "career", ["semester-gpa-target-calculator", "college-gpa-projector", "study-time-planner"], "You&rsquo;re at 82% and want an A &mdash; what do you need on the final? Formula, tier label, and a fallback if the target is mathematically impossible.", ["Enter current average.", "Enter final weight + target.", "Read grade needed."]],
  ["cefr-language-level-test", "CefrLanguageLevelTest", "CEFR Language Level Test", "Self-assessment quiz mapping to A1-C2 European Framework level. 10 questions, description + next-level targets.", "cefr language level test", "career", ["citation-generator", "study-time-planner", "flashcard-study-estimator"], "Gauge your language level on the European Framework in 10 questions. Honest self-assessment only &mdash; no algorithm can replace a real test.", ["Rate yourself on 10 skills.", "Read CEFR level.", "See next-level targets."]],
  ["research-paper-reading-time", "ResearchPaperReadingTime", "Research Paper Reading Time Estimator", "How long to read an academic paper by density and method. Three-pass strategy tips.", "research paper reading time", "career", ["study-time-planner", "flashcard-study-estimator", "citation-generator"], "Dense 40-page paper &mdash; 20 minutes or 4 hours? Depends on density and how deep you&rsquo;re reading. Estimates + the three-pass strategy.", ["Enter pages and density.", "Pick reading method.", "Read time estimate."]],
  ["college-affordability-calculator", "CollegeAffordabilityCalculator", "College Affordability Calculator", "Can you afford this college? Annual gap, 4-year debt projection, post-grad monthly payment vs entry salary.", "college affordability", "career", ["fafsa-efc-estimator", "act-to-sat-converter", "college-gpa-projector"], "Sticker price × 4 years &mdash; minus aid &mdash; equals loan debt. And that post-grad payment eats 15-45% of an entry-level salary. Run the numbers before committing.", ["Enter cost + contribution.", "Enter scholarships.", "Read affordability tier."]],
  ["fafsa-efc-estimator", "FafsaEfcEstimator", "FAFSA EFC / SAI Estimator", "Rough Expected Family Contribution (now SAI) estimator from parent income, assets, and household size.", "fafsa efc estimator", "career", ["college-affordability-calculator", "college-gpa-projector", "act-to-sat-converter"], "Rough EFC / SAI before you file the FAFSA. Simplified math &mdash; actual number comes from the official worksheet.", ["Enter parent income + assets.", "Enter household info.", "Read estimated EFC."]],
  ["flashcard-study-estimator", "FlashcardStudyEstimator", "Flashcard Study Time Estimator", "Cards needed + study hours for N concepts at target retention. Spaced-repetition review schedule.", "flashcard study estimator", "career", ["study-time-planner", "research-paper-reading-time", "semester-gpa-target-calculator"], "Retention isn&rsquo;t linear &mdash; 6 months requires 2x the reviews of 1 month. Cards, hours, and an SM-2-style review schedule from day 1 to 90.", ["Enter concepts + subject type.", "Pick target retention.", "Read cards + hours + schedule."]],
  ["test-score-percentile-lookup", "TestScorePercentileLookup", "Test Score Percentile Lookup", "Percentile rank for SAT, ACT, GRE, GMAT, LSAT, MCAT, IELTS, TOEFL. Top 10% reference score.", "test score percentile", "career", ["act-to-sat-converter", "college-affordability-calculator", "college-gpa-projector"], "Scored a 1400 SAT &mdash; that&rsquo;s 94th percentile. Look up any standardized-test score and see where you stand against the distribution.", ["Pick test.", "Enter your score.", "Read percentile + tier."]],

  // Events (10) — home for planning
  ["wedding-budget-calculator", "WeddingBudgetCalculator", "Wedding Budget Calculator", "Full wedding budget by region and guest count. 11-category split, per-guest cost, tier label.", "wedding budget calculator", "home", ["wedding-guest-list-splitter", "catering-cost-estimator", "cake-servings-calculator"], "Wedding costs break down predictably. Enter guest count and region, get a full 11-category budget with per-guest spend.", ["Enter guests or budget.", "Pick region.", "Read full breakdown."]],
  ["wedding-guest-list-splitter", "WeddingGuestListSplitter", "Wedding Guest List Splitter", "Allocate guest slots between families fairly. Even / contribution-based / custom methods.", "wedding guest list splitter", "home", ["wedding-budget-calculator", "rsvp-tracker", "seating-chart-generator"], "Two (or three) families, one guest list. Split evenly, by who pays what, or by custom percentage &mdash; plus a must-haves-first worksheet.", ["Enter total guests + families.", "Pick split method.", "Read per-family slots."]],
  ["seating-chart-generator", "SeatingChartGenerator", "Seating Chart Generator", "Assign guests to tables with group-preserving logic. Printable chart with overflow warnings.", "seating chart generator", "home", ["rsvp-tracker", "wedding-guest-list-splitter", "wedding-budget-calculator"], "Paste a list of guests (tagged into groups), pick tables and seats. The tool keeps groups together and flags overflow.", ["Paste guests by line.", "Set tables and seats.", "Copy printable chart."]],
  ["cake-servings-calculator", "CakeServingsCalculator", "Wedding Cake Servings Calculator", "Cake size for N guests. Wilton serving chart, tier configuration recommendations.", "wedding cake servings", "home", ["wedding-budget-calculator", "bar-quantity-calculator", "catering-cost-estimator"], "Wilton&rsquo;s wedding slice (1x2&quot;) vs a party slice (1.5x2&quot;) &mdash; different servings per tier. Round or square, single or stacked, full chart.", ["Enter guest count.", "Pick slice size + shape.", "Read recommended tiers."]],
  ["bar-quantity-calculator", "BarQuantityCalculator", "Bar Quantity Calculator", "Alcohol for any party. 1-drink-per-hour baseline adjusted for drinker type, by beer/wine/spirits split.", "bar quantity calculator", "home", ["cake-servings-calculator", "wedding-budget-calculator", "catering-cost-estimator"], "Don&rsquo;t run dry. 1 drink per guest per hour, tuned for your crowd&rsquo;s drinking style, split across beer/wine/spirits.", ["Enter guests + hours.", "Set drinker type + splits.", "Read bottles needed."]],
  ["catering-cost-estimator", "CateringCostEstimator", "Catering Cost Estimator", "Full catering cost by service style, cuisine tier, and guest count. Service fees, tax, bartender included.", "catering cost estimator", "home", ["wedding-budget-calculator", "bar-quantity-calculator", "cake-servings-calculator"], "Buffet vs plated vs family-style: huge price differences. Full cost breakdown including 20% service fee and 1 bartender per 75 guests.", ["Pick style + cuisine tier.", "Enter guests + bar needs.", "Read full cost."]],
  ["save-the-date-timing", "SaveTheDateTiming", "Save-the-Date Timing Guide", "Days-until for save-the-dates, invites, RSVPs, and final headcount based on your wedding date.", "save the date timing", "home", ["wedding-budget-calculator", "rsvp-tracker", "wedding-guest-list-splitter"], "6 milestones on a wedding timeline with days-until countdown. Different schedule for destination and holiday weddings.", ["Enter wedding date and type.", "Read milestone dates.", "Print the checklist."]],
  ["party-food-quantity-calculator", "PartyFoodQuantityCalculator", "Party Food Quantity Calculator", "Food quantities for any party. Appetizers, mains, sides, drinks with grocery cost estimate.", "party food quantity", "home", ["bar-quantity-calculator", "catering-cost-estimator", "cake-servings-calculator"], "6 oz protein + 4 oz per side + 8 bites if apps. Per-person quantities for 4 party types, total shopping list, cost estimate at typical grocery prices.", ["Enter guests + hours.", "Pick meal type.", "Read quantities + cost."]],
  ["wedding-registry-prioritizer", "WeddingRegistryPrioritizer", "Wedding Registry Prioritizer", "5-tier price structure ($25 to $250) based on guest count and goal. Must-have / nice-to-have / stretch.", "wedding registry prioritizer", "home", ["wedding-budget-calculator", "wedding-guest-list-splitter", "save-the-date-timing"], "Half your guests don&rsquo;t use the registry. The other half want 5 price tiers to pick from. This builds that structure.", ["Enter goal + guest count.", "Read tier suggestions.", "Allocate across categories."]],
  ["rsvp-tracker", "RsvpTracker", "RSVP Tracker", "Accept/decline/pending counts, response rate, and meal tallies from a textarea guest list.", "rsvp tracker", "home", ["wedding-guest-list-splitter", "seating-chart-generator", "save-the-date-timing"], "Paste your guest list with status tags, get completion stats, projected final attendance, and meal tallies. Tracks pending follow-ups.", ["Paste guests with statuses.", "Read response rates.", "Export follow-up list."]],
];

let toolSrc = readFileSync("components/tools/registry.tsx", "utf8");
const toolImports = tools.map(([, cls]) => `const ${cls} = dynamic(() => import("./${cls}").then(m => ({ default: m.${cls} })), { loading: Skeleton });`).join("\n");
const registryAnchor = `export const TOOL_REGISTRY: Record<string, ToolEntry> = {`;
toolSrc = toolSrc.replace(registryAnchor, `// Wave 3 education + events (22 new)\n${toolImports}\n\n${registryAnchor}`);
const lastRegEnd = toolSrc.lastIndexOf("};");
const toolEntries = tools.map(([slug, cls, , , , , , explainer, howToUse]) => {
  const howToStr = howToUse.map((s) => `      "${s.replace(/"/g, '\\"')}",`).join("\n");
  return `  "${slug}": {\n    render: () => <${cls} />,\n    explainer: (\n      <>\n        <p>${explainer}</p>\n        <p>\n          Runs entirely in your browser — no upload, no account, no watermark.\n          For more tools in this category see the{" "}\n          <a href="/tools">full tools index</a>.\n        </p>\n      </>\n    ),\n    howToUse: [\n${howToStr}\n    ],\n  },`;
}).join("\n");
toolSrc = toolSrc.slice(0, lastRegEnd) + toolEntries + "\n" + toolSrc.slice(lastRegEnd);
writeFileSync("components/tools/registry.tsx", toolSrc);
console.log("registry patched:", tools.length);

let pages = readFileSync("lib/pages.ts", "utf8");
const marker = "export const PAGES: Page[] = [";
const markerStart = pages.indexOf(marker);
const openBracket = markerStart + marker.length - 1;
let depth = 1, i = openBracket + 1, inStr = false, q = "", esc = false;
while (i < pages.length && depth > 0) {
  const c = pages[i];
  if (inStr) { if (esc) esc = false; else if (c === "\\") esc = true; else if (c === q) inStr = false; }
  else if (c === '"' || c === "'" || c === "`") { inStr = true; q = c; }
  else if (c === "[") depth++;
  else if (c === "]") depth--;
  i++;
}
const closeBracket = i - 1;
const esc2 = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const manifestEntries = tools.map(([slug, , title, description, keyword, category, related]) => {
  const relatedArr = related.map((s) => `"${s}"`).join(", ");
  return `  { slug: "${slug}", type: "tool", category: "${category}",\n    title: "${esc2(title)}",\n    h1: "${esc2(title)}",\n    description: "${esc2(description)}",\n    keyword: "${keyword}",\n    related: [${relatedArr}],\n    published: true },`;
}).join("\n");
pages = pages.slice(0, closeBracket) + "\n" + manifestEntries + "\n" + pages.slice(closeBracket);
writeFileSync("lib/pages.ts", pages);
console.log("manifest patched:", tools.length);
