// Wire Wave 4: 10 creator + 10 shopping tools
import { readFileSync, writeFileSync } from "node:fs";

const tools = [
  // Creator economy (10) - fit under career (monetization) and money
  ["youtube-revenue-estimator", "YoutubeRevenueEstimator", "YouTube Revenue Estimator", "Ad revenue + memberships + sponsorships from monthly views. Niche-aware CPM modifiers.", "youtube revenue estimator", "career", ["tiktok-creator-fund-calculator", "sponsorship-rate-estimator", "creator-tax-reserve"], "Monthly view count in, monthly revenue out. 6 niches with real CPM differences &mdash; finance is 7x gaming. Plus membership and sponsorship layers.", ["Enter monthly views + niche.", "Set watch time %.", "Read monthly + yearly revenue."]],
  ["tiktok-creator-fund-calculator", "TiktokCreatorFundCalculator", "TikTok Creator Fund Calculator", "Creator Fund and Creativity Program earnings from monthly views. Honest numbers on both.", "tiktok creator fund", "career", ["youtube-revenue-estimator", "sponsorship-rate-estimator", "instagram-engagement-rate"], "Creator Fund pays $0.02-0.04 per 1000 views (dying). Creativity Program: $4-8 per 1000 (for qualifying videos). The truth about TikTok monetization.", ["Enter monthly views.", "Set engagement rate.", "Read both program earnings."]],
  ["instagram-engagement-rate", "InstagramEngagementRate", "Instagram Engagement Rate Calculator", "Engagement rate % from followers + likes + comments + saves. Tier vs account size.", "instagram engagement rate", "career", ["tiktok-creator-fund-calculator", "sponsorship-rate-estimator", "youtube-revenue-estimator"], "ER tells brands more than follower count. Here&rsquo;s yours vs the median for your account size. 3-6% is good; 6%+ is great.", ["Enter followers + avg post metrics.", "Read ER %.", "Compare to median for your size."]],
  ["twitch-sub-revenue-calculator", "TwitchSubRevenueCalculator", "Twitch Subscription Revenue Calculator", "Monthly Twitch income: subs (tier 1/2/3), bits, ads. 50% vs 70% revenue share.", "twitch subscription revenue", "career", ["youtube-revenue-estimator", "sponsorship-rate-estimator", "creator-tax-reserve"], "Subs at $4.99/$9.99/$24.99 with creator share, plus bits at $0.01 each, plus ad revenue at typical CPMs. Full monthly breakdown.", ["Enter subs by tier + bits + CCV.", "Pick revenue share.", "Read monthly income."]],
  ["onlyfans-earnings-calculator", "OnlyfansEarningsCalculator", "OnlyFans Earnings Calculator", "Estimated monthly revenue from subs, tips, and PPV. Platform cut (20%) applied to net.", "onlyfans earnings", "career", ["sponsorship-rate-estimator", "creator-tax-reserve", "ugc-rate-calculator"], "Gross from subs + tips + PPV, minus the 20% platform fee. Focus on revenue-per-user, not sub count.", ["Enter subs and price.", "Enter tip + PPV rates.", "Read gross and net."]],
  ["sponsorship-rate-estimator", "SponsorshipRateEstimator", "Sponsorship Rate Estimator", "Brand deal pricing by platform, follower count, engagement rate, and niche. Low/mid/high ranges.", "sponsorship rate estimator", "career", ["youtube-revenue-estimator", "tiktok-creator-fund-calculator", "ugc-rate-calculator"], "What should you charge for a sponsored post? Rates by platform, follower count, engagement, and niche. Plus negotiation tips.", ["Pick platform + niche.", "Enter followers + ER.", "Read rate range."]],
  ["ugc-rate-calculator", "UgcRateCalculator", "UGC Rate Calculator", "UGC creator pricing by tier, deliverable, and usage rights. Paid ads cost 2-3x organic.", "ugc rate calculator", "career", ["sponsorship-rate-estimator", "creator-tax-reserve", "onlyfans-earnings-calculator"], "UGC is different from influencer &mdash; you charge for content, not audience. Rates by tier and deliverable, with usage-rights uplift.", ["Pick tier + deliverable.", "Set usage rights.", "Read rate range."]],
  ["creator-tax-reserve", "CreatorTaxReserve", "Creator Tax Reserve Calculator", "Self-employment tax + federal + state reserve % for creator income. Quarterly estimated payments.", "creator tax reserve", "money", ["freelancer-tax-reserve-calculator", "youtube-revenue-estimator", "onlyfans-earnings-calculator"], "SE tax 15.3% plus federal + state. Creators get hit with IRS penalties for underpaying. This gets you the quarterly number to send in.", ["Enter gross + expenses.", "Pick state + filing status.", "Read total reserve %."]],
  ["podcast-cpm-calculator", "PodcastCpmCalculator", "Podcast CPM Calculator", "Podcast ad revenue from monthly downloads × ads × CPM. Host-read commands 2x programmatic.", "podcast cpm calculator", "career", ["youtube-revenue-estimator", "sponsorship-rate-estimator", "newsletter-revenue-calculator"], "Host-read podcast ads: $20-30 CPM mid-roll. Programmatic: half that. Your monthly downloads × ads per episode × placement CPM.", ["Enter downloads + episodes.", "Set ad count + placement.", "Read monthly revenue."]],
  ["newsletter-revenue-calculator", "NewsletterRevenueCalculator", "Newsletter Revenue Calculator", "Revenue projection by monetization model: ads, paid sub, paid+free, affiliate, sponsored posts.", "newsletter revenue calculator", "career", ["podcast-cpm-calculator", "sponsorship-rate-estimator", "creator-tax-reserve"], "Ads vs paid sub vs affiliate &mdash; the math is wildly different. See projected monthly revenue by model plus a size-based recommendation.", ["Enter subs + open rate.", "Pick monetization model.", "Read monthly revenue."]],

  // Shopping / sizing (10) - fit under converters
  ["clothing-size-converter", "ClothingSizeConverter", "Clothing Size Converter US EU UK JP", "Men&rsquo;s and women&rsquo;s clothing sizes across US, EU, UK, Japan, Australia. All categories.", "clothing size converter", "converters", ["shoe-size-converter", "jeans-waist-converter", "kids-clothing-size-by-age"], "US 8 = UK 12 = EU 40 = JP 13 &mdash; but only for women&rsquo;s tops. Men&rsquo;s, dresses, pants all different tables. All of them here.", ["Pick gender + category.", "Enter size + country.", "Read all equivalents."]],
  ["shoe-size-converter", "ShoeSizeConverter", "Shoe Size Converter", "Men&rsquo;s, women&rsquo;s, kids shoe sizes US ↔ UK ↔ EU ↔ JP. Foot length in cm.", "shoe size converter", "converters", ["clothing-size-converter", "ring-size-converter", "kids-clothing-size-by-age"], "Women&rsquo;s US 8 = UK 6 = EU 38-39 = JP 25. Men&rsquo;s, kids too. Plus foot length in cm to verify against your actual foot.", ["Pick gender + source country.", "Enter size.", "Read all equivalents."]],
  ["ring-size-converter", "RingSizeConverter", "Ring Size Converter US UK EU JP mm", "Ring size US, UK, EU, Japan, plus circumference in mm. Home measurement tips included.", "ring size converter", "converters", ["clothing-size-converter", "watch-case-size-guide", "bra-size-converter"], "US 7 = UK N = EU 54 = JP 14 = 54.4mm circumference. Five systems plus a string-and-ruler home-measurement guide.", ["Enter size or circumference.", "Pick source country.", "Read all equivalents."]],
  ["bra-size-converter", "BraSizeConverter", "Bra Size Converter", "US ↔ UK ↔ EU ↔ AU bra sizes. Sisterhood-size explainer (32D = 34C = 30DD).", "bra size converter", "converters", ["clothing-size-converter", "jeans-waist-converter", "kids-clothing-size-by-age"], "Bra sizing across 4 countries + the sisterhood-size rule (same volume, different band/cup combos). With cup-letter divergence above DD.", ["Enter band + cup + country.", "Read all equivalents.", "Check sister sizes."]],
  ["watch-case-size-guide", "WatchCaseSizeGuide", "Watch Case Size Guide", "Match watch case diameter to wrist circumference. Strap width and lug-to-lug guidance.", "watch case size", "converters", ["ring-size-converter", "clothing-size-converter", "shoe-size-converter"], "7-inch wrist wants a 40mm watch. Plus strap width (case/2) and why lug-to-lug matters more than diameter on skinny wrists.", ["Enter wrist size.", "Read case size range.", "See strap width + thickness."]],
  ["luggage-weight-checker", "LuggageWeightChecker", "Luggage Weight & Size Checker", "Baggage allowance by airline + class. 30+ carriers with pack-within weight targets.", "luggage weight checker", "converters", ["travel-budget-calculator", "flight-time-calculator", "clothing-size-converter"], "30 airlines, 4 classes, 3 trip types. Pack-within weight target built in (3 lbs buffer avoids $75-200 overweight fees). With per-airline notes.", ["Pick airline + class.", "Pick trip type.", "Read allowances + target."]],
  ["jeans-waist-converter", "JeansWaistConverter", "Jeans Waist Size Converter", "Jeans waist US ↔ EU ↔ UK for men and women. Plus waist cm. Measurement guide.", "jeans waist converter", "converters", ["clothing-size-converter", "shoe-size-converter", "bra-size-converter"], "Men&rsquo;s 32 = EU 48 = UK 32. Women&rsquo;s 28 = EU 40 = UK 12. Plus waist in cm and a how-to-measure-accurately guide.", ["Pick gender + country.", "Enter size.", "Read all equivalents."]],
  ["hat-size-converter", "HatSizeConverter", "Hat Size Converter", "Hat size US fractional ↔ UK ↔ EU ↔ letter (XS-XXL). Head circumference in cm.", "hat size converter", "converters", ["clothing-size-converter", "glove-size-converter", "shoe-size-converter"], "US 7 fits a 56cm head &mdash; but is that S, M, or L? This maps all four systems with the string-and-ruler measurement technique.", ["Measure head in cm.", "Or enter a size.", "Read all systems."]],
  ["glove-size-converter", "GloveSizeConverter", "Glove Size Converter", "Glove size by palm circumference: US letter, EU number. Material-fit advice included.", "glove size converter", "converters", ["hat-size-converter", "clothing-size-converter", "shoe-size-converter"], "7&quot; palm = women&rsquo;s S. 8&quot; palm = men&rsquo;s M. With material-fit notes (leather stretches, wool fits tight, liners size up).", ["Measure palm circumference.", "Pick gender.", "Read size + fit tips."]],
  ["kids-clothing-size-by-age", "KidsClothingSizeByAge", "Kids Clothing Size by Age + Height", "Children&rsquo;s clothing size from age + height + weight. Height is the primary signal.", "kids clothing size", "converters", ["clothing-size-converter", "shoe-size-converter", "baby-weight-percentile"], "Kids come in all sizes. Use height first (most reliable), age second, weight for checks. From newborn 3M through Youth XL.", ["Enter age + height.", "Add weight if helpful.", "Read recommended size."]],
];

let toolSrc = readFileSync("components/tools/registry.tsx", "utf8");
const toolImports = tools.map(([, cls]) => `const ${cls} = dynamic(() => import("./${cls}").then(m => ({ default: m.${cls} })), { loading: Skeleton });`).join("\n");
const registryAnchor = `export const TOOL_REGISTRY: Record<string, ToolEntry> = {`;
toolSrc = toolSrc.replace(registryAnchor, `// Wave 4 creator + shopping (20 new)\n${toolImports}\n\n${registryAnchor}`);
const lastRegEnd = toolSrc.lastIndexOf("};");
const toolEntries = tools.map(([slug, cls, , , , , , explainer, howToUse]) => {
  const howToStr = howToUse.map((s) => `      "${s.replace(/"/g, '\\"')}",`).join("\n");
  return `  "${slug}": {\n    render: () => <${cls} />,\n    explainer: (\n      <>\n        <p>${explainer}</p>\n        <p>\n          Runs entirely in your browser — no upload, no account, no watermark.\n          For more tools in this category see the{" "}\n          <a href="/tools">full tools index</a>.\n        </p>\n      </>\n    ),\n    howToUse: [\n${howToStr}\n    ],\n  },`;
}).join("\n");
toolSrc = toolSrc.slice(0, lastRegEnd) + toolEntries + "\n" + toolSrc.slice(lastRegEnd);
writeFileSync("components/tools/registry.tsx", toolSrc);
console.log("registry patched:", tools.length);

let pages = readFileSync("lib/pages.ts", "utf8");
const marker = "export const PAGES: Page[] = [";
const markerStart = pages.indexOf(marker);
const openBracket = markerStart + marker.length - 1;
let depth = 1, i = openBracket + 1, inStr = false, q = "", esc = false;
while (i < pages.length && depth > 0) {
  const c = pages[i];
  if (inStr) { if (esc) esc = false; else if (c === "\\") esc = true; else if (c === q) inStr = false; }
  else if (c === '"' || c === "'" || c === "`") { inStr = true; q = c; }
  else if (c === "[") depth++;
  else if (c === "]") depth--;
  i++;
}
const closeBracket = i - 1;
const esc2 = (s) => String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
const manifestEntries = tools.map(([slug, , title, description, keyword, category, related]) => {
  const relatedArr = related.map((s) => `"${s}"`).join(", ");
  return `  { slug: "${slug}", type: "tool", category: "${category}",\n    title: "${esc2(title)}",\n    h1: "${esc2(title)}",\n    description: "${esc2(description)}",\n    keyword: "${keyword}",\n    related: [${relatedArr}],\n    published: true },`;
}).join("\n");
pages = pages.slice(0, closeBracket) + "\n" + manifestEntries + "\n" + pages.slice(closeBracket);
writeFileSync("lib/pages.ts", pages);
console.log("manifest patched:", tools.length);
